{
    "common-0": "「灵击符」",
    "common-1": "「Magic Potion」(魔法药水)",
    "common-2": "「Stop Watch」(时停怀表)",
    "common-3": "「白楼剑」",
    "common-4": "「替身人偶」",
    "common-5": "「Grimoire」(魔法书)",
    "common-6": "「特别定制的太阳伞」",
    "common-7": "「人魂灯」",
    "common-8": "「左扇」",
    "common-9": "「伊吹瓢」",
    "common-10": "「天狗团扇」",
    "common-11": "「符蚀药」",
    "common-12": "「隔夜钱」",
    "common-13": "「龙鱼的羽衣」",
    "common-14": "「绯想之剑」",
    "common-15": "「病气平愈护符」",
    "common-16": "「冰冻青蛙」",
    "common-17": "「龙星」",
    "common-18": "「控制棒」",
    "common-19": "「三粒之天滴」",
    "common-20": "「鲶鱼的大地震」",
    "reimu-0": "御守「妖怪拘禁符」",
    "reimu-4": "灵符「梦想封印　圆」",
    "reimu-8": "神灵「梦想封印　瞬」",
    "reimu-12": "「最凶恶的吓人巫女玉」",
    "reimu-111": "祈雨之仪",
    "reimu-204": "梦符「封魔阵」",
    "reimu-207": "结界「扩散结界」",
    "marisa-0": "星符「Eccentric Asteroid」(离心的小行星)",
    "marisa-4": "流光「Shooting Echo」(射击回声)",
    "marisa-8": "魔符「Magical R360」(魔法全方位)",
    "marisa-110": "魔法废物再利用炸弹",
    "marisa-204": "恋符「Non-Directional Laser」(非定向光线)",
    "marisa-209": "星符「Gravity Beat」(重力一击)",
    "marisa-212": "光符「Earth Light Ray」(地球光)",
    "marisa-214": "魔废「Deep Ecological Bomb」(深层生态炸弹)",
    "sakuya-108": "Dancing Star Sword",
    "sakuya-109": "Misdirection",
    "sakuya-110": "Parallel Brane",
    "sakuya-111": "Time Paradox",
    "sakuya-210": "光速「C. Ricochet」(光速跃迁)",
    "sakuya-211": "时符「Imaginary Vertical Time」(假想时轴)",
    "sakuya-212": "时计「Luna Dial」(月时计)",
    "alice-0": "人偶「Semi-Automaton」(半自主人偶)",
    "alice-4": "骑士「Doll of Round Table」(圆桌人偶)",
    "alice-8": "牺牲「Suicide Pact」(自杀协议)",
    "alice-12": "试验中「Level Titania」(提泰妮娅级)",
    "alice-16": "试验中「歌利亚人偶」",
    "alice-108": "人偶伏兵",
    "alice-110": "人偶弓兵",
    "alice-210": "枪符「萌萌大千枪」",
    "alice-211": "人偶「Lemmings' Parade」(旅鼠的盛装游行)",
    "patchouli-0": "火符「Ring of Agni」(天火神印)",
    "patchouli-4": "水符「Princess Undine」(水精公主)",
    "patchouli-110": "Wipe Moisture",
    "patchouli-111": "Sticky Bubbles",
    "patchouli-112": "Static Green",
    "patchouli-113": "Fall Slasher",
    "patchouli-114": "Diamond Hardness",
    "patchouli-211": "火水符「Phlogistic Pillar」(燃素之柱)",
    "patchouli-212": "土金符「Emerald Megalopolis」(翡翠巨城)",
    "patchouli-213": "日月符「Royal Diamond Ring」(皇家钻戒)",
    "youmu-108": "燐气斩",
    "youmu-110": "头上花剪斩",
    "youmu-208": "空观剑「六根清净斩」",
    "youmu-212": "转生剑「圆心流转斩」",
    "remilia-108": "Trickster Devil",
    "remilia-110": "Vampire Kiss",
    "remilia-111": "Stigmatizer",
    "remilia-208": "「千年吸血鬼」",
    "remilia-209": "恶魔「Remilia Stretch」(蕾米莉亚伸展)",
    "yuyuko-109": "死还的大地",
    "yuyuko-110": "故人的遗物",
    "yuyuko-111": "Sense of Elegance",
    "yuyuko-209": "樱符「Sense of Cherry Blossom」(樱之意志)",
    "yuyuko-219": "「反魂蝶」",
    "yukari-109": "知能与脚的境界",
    "yukari-110": "静观其变之眼",
    "yukari-111": "奇美拉之翼",
    "yukari-208": "魔眼「拉普拉斯之魔」",
    "suika-108": "踏鞴",
    "suika-110": "鬼神燐火术",
    "suika-111": "攫鬼",
    "suika-212": "四天王奥义「三步坏废」",
    "reisen-111": "Ocular Spectrum",
    "reisen-204": "赤眼「望见圆月(Lunatic Blast)」",
    "reisen-210": "短视「超短脑波(X Wave)」",
    "reisen-211": "长视「赤月下(Infrared Moon)」",
    "aya-108": "枫扇风",
    "aya-111": "天狗砾",
    "aya-207": "风符「天狗报当日截稿」",
    "aya-208": "鸦符「暗夜昼魇」",
    "komachi-109": "三途之舟",
    "komachi-111": "离魂之镰",
    "komachi-207": "魂符「生魂流离的镰刀」",
    "iku-108": "龙鱼得水",
    "iku-109": "天女的一击",
    "iku-110": "龙神之须",
    "iku-208": "羽衣「羽衣若时」",
    "iku-211": "珠符「五爪龙之珠」",
    "tenshi-108": "因果之剑",
    "tenshi-109": "地精的起床",
    "tenshi-110": "绯想的剑气",
    "tenshi-111": "升天突",
    "tenshi-208": "剑技「气焰万丈之剑」",
    "tenshi-209": "天气「绯想天促」",
    "sanae-0": "蛇符「云泳大蛇」",
    "sanae-4": "奇迹「空中落物的奇迹」",
    "sanae-100": "唤风",
    "sanae-101": "御神签炸弹",
    "sanae-102": "乾神招来　突",
    "sanae-103": "坤神招来　盾",
    "sanae-104": "起浪",
    "sanae-105": "Sky Serpent",
    "sanae-106": "乾神招来　风",
    "sanae-107": "坤神招来　铁轮",
    "sanae-108": "星落",
    "sanae-109": "Cobalt Spread",
    "sanae-110": "乾神招来　御柱",
    "sanae-111": "坤神招来　陷阱",
    "sanae-200": "祈愿「守护商业繁荣」",
    "sanae-201": "秘术「Gray Thaumaturgy」(灰色奇术)",
    "sanae-202": "秘术「遗忘之祭仪」",
    "sanae-203": "神签「暴乱神签连掷」",
    "sanae-204": "开海「海水分开之日」",
    "sanae-205": "开海「摩西之奇迹」",
    "sanae-206": "奇迹「白昼的客星」",
    "sanae-207": "奇迹「客星辉煌之夜」",
    "sanae-210": "秘法「九字切」",
    "cirno-0": "冰符「Icicle Fall」(冰瀑)",
    "cirno-4": "冻符「Minus K」(负K)",
    "cirno-100": "Icicle Shoot",
    "cirno-101": "盛夏的雪人",
    "cirno-102": "Little Iceberg",
    "cirno-103": "Freeze Touch Me",
    "cirno-104": "Frost Pillars",
    "cirno-105": "Ice Charge",
    "cirno-106": "Icicle Bomb",
    "cirno-107": "Icicle Rise",
    "cirno-108": "冷冻光线",
    "cirno-109": "Ice Kick",
    "cirno-110": "急冻冷冻法",
    "cirno-111": "Icicle Sword",
    "cirno-200": "冰符「Icicle Machine Gun」(冰柱机枪)",
    "cirno-201": "霜符「Frost Columns」(冰袭方阵)",
    "cirno-202": "冰块「Cold Sprinkler」(冷冻洒水器)",
    "cirno-203": "冷体「Super Ice Kick」(超级回旋冰踢)",
    "cirno-204": "冻符「Perfect Freeze」(完美冻结)",
    "cirno-205": "冰符「Fairy Spin」(妖精旋转)",
    "cirno-206": "吹冰「Ice Tornado」(碎冰龙卷)",
    "cirno-207": "冰符「Sword Freezer」(剑式制冰器)",
    "cirno-208": "冰块「Great Crusher」(巨冰破碎)",
    "cirno-210": "冻符「Freeze Atmosphere」(急冻大气)",
    "cirno-213": "冷符「瞬间冷冻光线」",
    "meiling-0": "彩翔「飞花落叶」",
    "meiling-4": "彩符「极彩沛雨」",
    "meiling-100": "螺光步",
    "meiling-101": "红炮",
    "meiling-102": "黄震脚",
    "meiling-103": "芳波",
    "meiling-104": "烈虹拳",
    "meiling-105": "红寸劲",
    "meiling-106": "地龙波",
    "meiling-107": "水形太极拳",
    "meiling-108": "降华蹴",
    "meiling-109": "虎劲",
    "meiling-110": "天龙脚",
    "meiling-111": "彩雨",
    "meiling-200": "彩符「彩光风铃」",
    "meiling-201": "极彩「彩光乱舞」",
    "meiling-202": "气符「星脉弹」",
    "meiling-203": "星气「星脉地转弹」",
    "meiling-204": "击符「大鹏拳」",
    "meiling-205": "炽击「大鹏坠击拳」",
    "meiling-206": "虹符「烈虹真拳」",
    "meiling-207": "气符「地龙天龙脚」",
    "meiling-208": "彩华「虹色太极拳」",
    "meiling-209": "华符「彩光莲华掌」",
    "meiling-211": "气符「猛虎内劲」",
    "utsuho-0": "热符「Break Prominence」(破碎日珥)",
    "utsuho-4": "核热「核反应失控疾冲」",
    "utsuho-8": "「热木星降落模型」",
    "utsuho-12": "核热「人工太阳的黑子」",
    "utsuho-100": "Flare Up",
    "utsuho-101": "Ground Melt",
    "utsuho-102": "Break Sun",
    "utsuho-103": "Shooting Star",
    "utsuho-104": "Rocket Dive",
    "utsuho-105": "Hell Geyser",
    "utsuho-106": "Shooting Sun",
    "utsuho-107": "复古原子核模型",
    "utsuho-108": "熔化转体踢",
    "utsuho-109": "Radiant Blade",
    "utsuho-110": "地狱波动炮",
    "utsuho-111": "核热的怨灵",
    "utsuho-200": "爆符「Mega-Flare」(百万耀斑)",
    "utsuho-201": "爆符「Giga-Flare」(十亿耀斑)",
    "utsuho-203": "焰星「Fixed Star」(恒星)",
    "utsuho-204": "焰星「十凶星」",
    "utsuho-205": "核符「Creeping Sun」(缓行的太阳)",
    "utsuho-206": "「地狱的人造太阳」",
    "utsuho-207": "地热「核焰喷涌」",
    "utsuho-208": "光热「High Tension Blade」(高压光刃)",
    "utsuho-209": "鸦符「八咫乌俯冲」",
    "utsuho-210": "核热「核反应失控疾冲」",
    "utsuho-211": "控制「Self Tokamak」(自动托卡马克装置)",
    "utsuho-212": "「Subterranean Sun」(地底太阳)",
    "utsuho-213": "遮光「核热护罩」",
    "utsuho-214": "「Abyss Nova」(深渊新星)",
    "suwako-0": "合掌「大太法师的参拜」",
    "suwako-4": "神具「洩矢的铁轮」",
    "suwako-8": "「炽如地狱的间歇泉」",
    "suwako-12": "「岩浆的两栖类」",
    "suwako-16": "「幻想乡空中神战」",
    "suwako-100": "古老的间歇泉",
    "suwako-101": "大蛤蟆神",
    "suwako-102": "大地之湖",
    "suwako-103": "土著神的作祟",
    "suwako-104": "水蛙神",
    "suwako-105": "古老铁轮",
    "suwako-106": "古代翡翠",
    "suwako-107": "诅咒的大地",
    "suwako-108": "招雨的雨蛙",
    "suwako-109": "手长足长先生",
    "suwako-110": "蛙石神",
    "suwako-111": "御社宫司大人的作祟",
    "suwako-200": "土著神「洩矢神」",
    "suwako-201": "源符「诹访清水」",
    "suwako-202": "开宴「二拜二拍一拜」",
    "suwako-203": "土著神「小小青蛙不输风雨」",
    "suwako-204": "神具「洩矢的铁轮」",
    "suwako-205": "源符「厌川的翡翠」",
    "suwako-206": "蛙狩「蛙以口鸣，方致蛇祸」",
    "suwako-207": "土著神「手长足长大人」",
    "suwako-208": "祟神「赤口大人」",
    "suwako-209": "土著神「宝永四年的赤蛙」",
    "suwako-212": "蛙休「总是能够冬眠」",
    "namazu-0": "鲶鱼「看哪，世界在震动哦？」",
    "namazu-4": "鲶鱼「土壤液化现象让大地也像泥一样了！」",
    "namazu-8": "鲶鱼「即使是发电也会努力哦？」",
    "namazu-12": "鲶鱼「全电气化更加环保！」",
    "namazu-16": "大鲶鱼「这一招出来，连尘世都要完结了！！」",
    "udonge-111": "Ocular Spectrum",
    "udonge-204": "赤眼「望见圆月(Lunatic Blast)」",
    "udonge-210": "短视「超短脑波(X Wave)」",
    "udonge-211": "长视「赤月下(Infrared Moon)」",
    "chirno-0": "冰符「Icicle Fall」(冰瀑)",
    "chirno-4": "冻符「Minus K」(负K)",
    "chirno-100": "Icicle Shot",
    "chirno-101": "盛夏的雪人",
    "chirno-102": "Little Iceberg",
    "chirno-103": "Freeze Touch Me",
    "chirno-104": "Frost Pillars",
    "chirno-105": "Ice Charge",
    "chirno-106": "Icicle Bomb",
    "chirno-107": "Icicle Rise",
    "chirno-108": "冷冻光线",
    "chirno-109": "Ice Kick",
    "chirno-110": "急冻冷冻法",
    "chirno-111": "Icicle Sword",
    "chirno-200": "冰符「Icicle Machine Gun」(冰柱机枪)",
    "chirno-201": "霜符「Frost Columns」(冰袭方阵)",
    "chirno-202": "冰块「Cold Sprinkler」(冷冻洒水器)",
    "chirno-203": "冷体「Super Ice Kick」(超级回旋冰踢)",
    "chirno-204": "冻符「Perfect Freeze」(完美冻结)",
    "chirno-205": "冰符「Fairy Spin」(妖精旋转)",
    "chirno-206": "吹冰「Ice Tornado」(碎冰龙卷)",
    "chirno-207": "冰符「Sword Freezer」(剑式制冰器)",
    "chirno-208": "冰块「Great Crusher」(巨冰破碎)",
    "chirno-210": "冻符「Freeze Atmosphere」(急冻大气)",
    "chirno-213": "冷符「瞬间冷冻光线」",
    "meirin-0": "彩翔「飞花落叶」",
    "meirin-4": "彩符「极彩沛雨」",
    "meirin-100": "螺光步",
    "meirin-101": "红炮",
    "meirin-102": "黄震脚",
    "meirin-103": "芳波",
    "meirin-104": "烈虹拳",
    "meirin-105": "红寸劲",
    "meirin-106": "地龙波",
    "meirin-107": "水形太极拳",
    "meirin-108": "降华蹴",
    "meirin-109": "虎劲",
    "meirin-110": "天龙脚",
    "meirin-111": "彩雨",
    "meirin-200": "彩符「彩光风铃」",
    "meirin-201": "极彩「彩光乱舞」",
    "meirin-202": "气符「星脉弹」",
    "meirin-203": "星气「星脉地转弹」",
    "meirin-204": "击符「大鹏拳」",
    "meirin-205": "炽击「大鹏坠击拳」",
    "meirin-206": "虹符「烈虹真拳」",
    "meirin-207": "气符「地龙天龙脚」",
    "meirin-208": "彩华「虹色太极拳」",
    "meirin-209": "华符「彩光莲华掌」",
    "meirin-211": "气符「猛虎内劲」"
}