{
    "Yukari boss 2": "黑色子弹对下仆无效",
    "New version 1": "有新版本",
    "New version 2": "请进行更新",
    "Random Select": "随机选择",
    "Game title": "东方凭依华　～ Antinomy of Common Flowers.",
    "No change": "不指定",
    "Joon 1": "A:近打击　  B:射击　  C:符卡射击",
    "Dir creation failed": "执行程序所需的目录创建失败了。",
    "Yukari boss": "切换到下仆来躲避红色蓄力攻击！",
    "Save replay": "要保存Replay吗？",
    "Continue": "要续关吗？",
    "Yes": "是",
    "No": "否",
    "Delete file": "删除这个文件吗？",
    "No file": "这里什么也没有",
    "Loading": "读取中……",
    "Can't use": "不可使用",
    "Duo": "二人",
    "Trio": "三人",
    "Squad": "四人"
}