{
    "reimu-1": "灵符「梦想封印」",
    "reimu-2": "神技「八方龙杀阵」",
    "reimu-3": "宝具「阴阳飞鸟井」",
    "reimu-lw": "＊在那隙间里面居然有个巫女！＊",
    "reimu-story-1": "灵鹰符「飞鹰的梦想封印狩猎」",
    "reimu-story-2": "灵符「梦想封印　梦限」",
    "reimu-story-against-shion": "「最强最棒的异变解决巫女」",
    "marisa-1": "恋符「Master Spark」(极限火花)",
    "marisa-2": "彗星「Blazing Star」(闪亮之星)",
    "marisa-3": "星符「Satellite Illusion」(卫星幻觉)",
    "marisa-story-1": "星恋符「Sprinkle Star & Heart」(星星心心洒)",
    "marisa-story-2": "星灵符「Sprinkle Star封印」(洒星封印)",
    "marisa-story-3": "星符「Asteroid Belt Nightmare」(小行星带噩梦)",
    "marisa-story-4": "针星符「封印月卿之针火花」",
    "marisa-lw": "＊真棒！厕所里的花子小姐！＊",
    "shion-story-2": "「最凶最恶的极贫不幸神」",
    "kasen-1": "包符「假肢变形」",
    "kasen-2": "龙符「Dragon's Growl」(巨龙之啸)",
    "kasen-3": "鹰符「Hawk Beacon」(飞鹰信标)",
    "kasen-story-1": "雷灵符「务光的雷弹梦想封印」",
    "kasen-story-2": "龙蹴符「巨龙飞鸟井之踢」",
    "kasen-story-3": "雷符「务光的雷霆闪光梦幻弹」",
    "kasen-story-4": "龙符「Dragon's Optical Dream」(巨龙光学迷梦)",
    "kasen-story-5": "雷化符「务光与叶叶的弹幕变化」",
    "kasen-story-6": "龙化符「Dragon's Alien Capsule」(巨龙外星人胶囊)",
    "kasen-lw": "＊猿之手啊！捏碎敌人！＊",
    "ichirin-1": "岚符「佛罚的秋台风」",
    "ichirin-2": "积乱「见越入道云」",
    "ichirin-3": "拳固「忏悔的杀风」",
    "ichirin-story-1": "拳风符「入道丛云风水拳」",
    "ichirin-story-2": "拳星符「入道丛云Slave Spark」(入道丛云下仆火花)",
    "ichirin-story-3": "拳水符「入道丛云水泡弹拳」",
    "ichirin-lw": "＊265厘米的魔人现身！＊",
    "hijiri-1": "天符「三千大千世界之主」",
    "hijiri-2": "天符「大日如来的光辉」",
    "hijiri-3": "天符「释迦牟尼的五行山」",
    "hijiri-story-1": "击拳符「韦驮天的怪云拳」",
    "hijiri-story-2": "击光符「韦驮天的王道威光」",
    "hijiri-story-3": "蹴斩符「迦楼罗的圣德斩」",
    "hijiri-story-4": "击符「被韦驮天追逐的正梦」",
    "hijiri-story-5": "光拳符「因陀罗的金刚杵怪云拳」",
    "hijiri-story-od": "光仙符「日出之国的僧侣和道士」",
    "hijiri-lw": "＊以100迈驰骋天际！＊",
    "futo-1": "风符「三轮的皿风暴」",
    "futo-2": "炎符「太乙真火」",
    "futo-3": "运气「破局的开门」",
    "futo-story-1": "风灵符「磐舟土器封印」",
    "futo-lw": "＊到死还是少一盘！＊",
    "miko-1": "仙符「日出之处的道士」",
    "miko-2": "道符「掌上的天道」",
    "miko-3": "人符「劝善惩恶古之良典」",
    "miko-story-1": "光击符「引导着你的王道的金刚杵射击」",
    "miko-story-2": "光符「引导着你的梦王道的威光」",
    "miko-story-3": "光风符「光辉风水披风」",
    "miko-lw": "＊特别让你两边都选！＊",
    "mamizou-1": "变化「分福热水浴」",
    "mamizou-2": "变化「百鬼妖界之门」",
    "mamizou-3": "变化「二岩家的制裁」",
    "mamizou-story-1": "化火符「妖怪弹幕变化 叶叶烨烨」",
    "mamizou-story-2": "化符「妖怪弹幕变化 梦见心地」",
    "mamizou-lw": "＊宇宙机密泄露！即刻处置＊",
    "mokou-1": "焰符「自灭火焰大旋风」",
    "mokou-2": "不死「凯风快晴飞翔蹴」",
    "mokou-3": "咒札「无差别放火之符」",
    "mokou-story-1": "火狂符「人体燃烧秘匿弹幕(Burning Hidden Bullet)」",
    "mokou-story-2": "「这不知是第几次的生命，梦想封印吧」",
    "mokou-lw": "＊这种世道赶紧烧个精光吧！＊",
    "sinmyoumaru-1": "小槌「传说中的大宴席」",
    "sinmyoumaru-2": "小人「一寸法师亦有五分之魂」",
    "sinmyoumaru-3": "钓符「可爱的太公望」",
    "shinmyoumaru-story-1": "槌恋符「大判小判叮叮当心」",
    "shinmyoumaru-story-2": "槌化符「大判小判弹幕变化」",
    "shinmyoumaru-story-3": "槌砾符「大判小判叮叮当念力」",
    "sinmyoumaru-lw": "＊绿巨人啊，变大吧！＊",
    "nitori-1": "暴雨「河底大战争」",
    "nitori-2": "泡符「射击吧！泡泡龙」",
    "nitori-3": "战机「飞翔吧！三平加油」",
    "nitori-story-1": "水面符「水泡弹假面舞会」",
    "nitori-lw": "＊尼斯湖现在就在这里！＊",
    "koishi-1": "抑制「Super Ego」(超我)",
    "koishi-2": "本能「本我的解放」",
    "koishi-3": "梦符「先祖大人在看着你」",
    "koishi-story-1": "恋拳符「玫瑰狂想曲怪云拳」",
    "koishi-lw": "＊现在就给你打电话别忘了接哦＊",
    "kokoro-1": "怒面「愤怒的忌狼之面」",
    "kokoro-2": "凭依「喜怒哀乐附体」",
    "kokoro-3": "忧面「杞人忧地」",
    "kokoro-story-1": "面风符「喜怒哀乐风水术」",
    "kokoro-story-2": "面符「喜怒哀乐发狂假面舞会」",
    "kokoro-lw": "＊就算这样，我也漂亮吧？＊",
    "usami-1": "铳符「3D Printer Gun」(3D打印枪)",
    "usami-2": "念力「Psychokinesis APP」(念力应用)",
    "usami-3": "念力「Telekinesis 通信塔」(隔空移物　通信塔)",
    "sumireko-story-1": "W超能力「Phychokinesis Teleportation」(念力传送)",
    "sumireko-story-2": "W超能力「绝体绝命都市人」",
    "sumireko-story-3": "超能力「Psychokinesis Endless」(念力无限)",
    "sumireko-story-od": "「世纪的二重超人 宇佐见堇子」",
    "usami-lw": "＊幻视吧！目睹异世界的狂气＊",
    "udonge-1": "「月面跳弹(Lunatic Double)」",
    "udonge-2": "「幻胧月睨(Lunatic Red Eyes)」",
    "udonge-3": "「地上跳弹(Lunatic Echo)」",
    "reisen-story-1": "狂槌符「狂视幻象(Disorder Eye)也变大吧」",
    "udonge-lw": "＊你已经疯了！＊",
    "doremy-1": "梦符「留绀色的逃走梦」",
    "doremy-2": "梦符「漆黑的宇宙梦」",
    "doremy-3": "羊符「Nightmare of Chimera」(奇美拉的噩梦)",
    "doremy-story-1": "梦砾符「羊毛色的念力」",
    "doremy-story-2": "梦要符「羊毛色的乾坤一掷」",
    "doremy-lw": "＊不用再醒来了哦＊",
    "yukari-1": "「无人废线车辆炸弹」",
    "yukari-2": "式神「八云蓝&橙」",
    "yukari-3": "境界「溢出的漂流物」",
    "yukari-story-1": "「{{ruby|凭坐|主役}}的忧郁」",
    "yukari-story-2": "「完全凭依与梦想封印」",
    "yukari-story-3": "「{{ruby|凭坐|主役}}与{{ruby|神灵|下仆}}的境界」",
    "yukari-lw": "＊把你美丽的脚拿来！＊",
    "tenshi-1": "要石「要石浮游炮」",
    "tenshi-2": "地符「一击震乾坤」",
    "tenshi-3": "桃符「固若金汤的仙桃」",
    "tenshi-story-1": "升符「飞向遥远的宇宙吧！ 载着我们的梦想」",
    "tenshi-story-2": "坠符「落入大气圈，梦想倾泻地表」",
    "tenshi-story-3": "「把大地重塑成，有梦的世界吧！」",
    "tenshi-story-4": "升槌符「载着我们的梦变大吧」",
    "tenshi-story-5": "坠槌符「梦坠入大气圈变大吧」",
    "tenshi-story-od-1": "「全小人族的绯想天」",
    "tenshi-story-od-2": "「巨型战舰 无双大鲶鱼参见」",
    "tenshi-story-od-3": "「全宇宙人的绯想天」",
    "tenshi-lw": "＊大气圈尽在吾之手中＊",
    "jyoon-1": "凭依剥夺「Slave Robber」(下仆强盗)",
    "jyoon-2": "贫符「超贫穷玉」",
    "jyoon-3": "「Queen of Bubble」(泡沫女王)",
    "joon-story-1": "不幸「欢迎来到极端贫困的世界」",
    "joon-story-2": "财祸「Pluck Pigeon」(雁过拔毛)",
    "joon-story-3": "凭依交换「Absolute Loser」(绝对输家)",
    "jyoon-lw": "「80年代的勒索者」",
    "shion-story-1": "贫符「Mischance Scatter」(厄运播撒)"
}