{
    "0": "月符「Moonlight Ray」(月光)",
    "1": "夜符「Night Bird」(夜雀)",
    "2": "暗符「Demarcation」(境界线)",
    "3": "冰符「Icicle Fall」(冰瀑)",
    "4": "雹符「Hailstorm」(冰雹暴风)",
    "5": "冻符「Perfect Freeze」(完美冻结)",
    "6": "雪符「Diamond Blizzard」(钻石风暴)",
    "7": "华符「芳华绚烂」",
    "8": "华符「Selaginella 9」(卷柏 9)",
    "9": "虹符「彩虹的风铃」",
    "10": "幻符「华想梦葛」",
    "11": "彩符「彩雨」",
    "12": "彩符「彩光乱舞」",
    "13": "彩符「极彩台风」",
    "14": "火符「Agni Shine」(火神之光)",
    "15": "水符「Princess Undine」(水精公主)",
    "16": "木符「Sylphy Horn」(风灵的角笛)",
    "17": "土符「Lazy Trilithon」(慵懒三石塔)",
    "18": "金符「Metal Fatigue」(金属疲劳)",
    "19": "火符「Agni Shine上级」(火神之光)",
    "20": "木符「Sylphy Horn上级」(风灵的角笛)",
    "21": "土符「Lazy Trilithon上级」(慵懒三石塔)",
    "22": "火符「Agni Radiance」(火神的光辉)",
    "23": "水符「Bury in Lake」(湖葬)",
    "24": "木符「Green Storm」(翠绿风暴)",
    "25": "土符「Trilithon Shake」(三石塔的震动)",
    "26": "金符「Silver Dragon」(银龙)",
    "27": "火&土符「Lava Cromlech」(环状熔岩带)",
    "28": "木&火符「Forest Blaze」(森林大火)",
    "29": "水&木符「Water Elf」(水精灵)",
    "30": "金&水符「Mercury Poison」(水银之毒)",
    "31": "土&金符「Emerald Megalith」(翡翠巨石)",
    "32": "奇术「Misdirection」(误导)",
    "33": "奇术「幻惑Misdirection」(幻惑误导)",
    "34": "幻在「Clock Corpse」(钟表的残骸)",
    "35": "幻象「Luna Clock」(月神之钟)",
    "36": "女仆秘技「操弄玩偶」",
    "37": "幻幽「Jack the Ludo Bile」(迷幻的杰克)",
    "38": "幻世「The World」(世界)",
    "39": "女仆秘技「杀人玩偶」",
    "40": "奇术「Eternal Meek」(永恒的温柔)",
    "41": "天罚「Star of David」(大卫之星)",
    "42": "冥符「红色的冥界」",
    "43": "诅咒「弗拉德·特佩斯的诅咒」",
    "44": "红符「Scarlet Shoot」(绯红之击)",
    "45": "「Red Magic」(红魔法)",
    "46": "神罚「年幼的恶魔之王」",
    "47": "狱符「千根针的针山」",
    "48": "神术「吸血鬼幻想」",
    "49": "红符「Scarlet Meister」(绯红之主)",
    "50": "「红色的幻想乡」",
    "51": "月符「Silent Selene」(沉静的月神)",
    "52": "日符「Royal Flare」(皇家圣焰)",
    "53": "火水木金土符「贤者之石」",
    "54": "禁忌「Cranberry Trap」(红莓陷阱)",
    "55": "禁忌「Laevatein」(莱瓦汀)",
    "56": "禁忌「Four of a Kind」(四重存在)",
    "57": "禁忌「Kagome Kagome」(笼中鸟)",
    "58": "禁忌「恋之迷宫」",
    "59": "禁弹「Starbow Break」(星弧破碎)",
    "60": "禁弹「Catadioptric」(折反射)",
    "61": "禁弹「刻着过去的钟表」",
    "62": "秘弹「之后就一个人都没有了吗？」",
    "63": "QED「495年的波纹」"
}