{
    "common-0": "「气质发现」",
    "common-1": "「灵击」",
    "common-2": "「防御反击」",
    "common-3": "「符力增幅」",
    "common-4": "「体力恢复」",
    "common-5": "「灵力恢复」",
    "reimu-0": "祈愿「祛除厄运之祈愿」",
    "reimu-4": "宝符「跳跃的阴阳玉」",
    "reimu-8": "梦境「二重大结界」",
    "reimu-12": "光灵「神灵宝珠」",
    "reimu-16": "「潜伏在境界内侧的灵与不可思议的巫女」",
    "reimu-100": "博丽护符",
    "reimu-101": "警醒阵",
    "reimu-102": "亚空穴",
    "reimu-103": "升天脚",
    "reimu-104": "妖怪破坏者",
    "reimu-105": "系缚阵",
    "reimu-106": "封魔亚空穴",
    "reimu-107": "抄地升天脚",
    "reimu-108": "扩散灵符",
    "reimu-109": "常置阵",
    "reimu-110": "刹那亚空穴",
    "reimu-200": "灵符「梦想妙珠」",
    "reimu-201": "神灵「梦想封印」",
    "reimu-206": "神技「八方鬼缚阵」",
    "reimu-209": "宝符「阴阳宝玉」",
    "reimu-210": "宝具「阴阳鬼神玉」",
    "reimu-214": "神技「天霸风神脚」",
    "reimu-219": "「梦想天生」",
    "reimu-208": "珠符「明珠暗投」",
    "marisa-0": "星符「Polaris Unique」(唯一的北极星)",
    "marisa-4": "天仪「Orrery's Universe」(宇宙仪)",
    "marisa-8": "邪恋「容易结果的Master Spark」",
    "marisa-100": "Witch Ley Line",
    "marisa-101": "Miasma Sweep",
    "marisa-102": "Ground Stardust",
    "marisa-103": "Meteonic Debris",
    "marisa-104": "Radial Strike",
    "marisa-105": "Bosky Sweeper",
    "marisa-106": "Devildom Torch",
    "marisa-107": "Narrow Spark",
    "marisa-108": "Up Sweep",
    "marisa-109": "Stellar Missile",
    "marisa-111": "Green Spread",
    "marisa-200": "恋符「Master Spark」(极限火花)",
    "marisa-202": "魔炮「Final Spark」(究极火花)",
    "marisa-203": "星符「Dragon Meteor」(龙流星)",
    "marisa-205": "魔符「Stardust Reverie」(星尘幻想)",
    "marisa-206": "星符「Escape Velocity」(逃逸速度)",
    "marisa-207": "彗星「Blazing Star」(彗星)",
    "marisa-208": "星符「Meteonic Shower」(流星雨)",
    "marisa-211": "光符「Luminous Strike」(光之冲击)",
    "marisa-215": "仪符「Orrery's Sun」(太阳仪)",
    "sakuya-0": "银符「Silver Bound」(银之跳跃)",
    "sakuya-4": "时符「咲夜特制秒表」",
    "sakuya-8": "幻术「My Knife Recursion」(吾刃回归)",
    "sakuya-12": "时符「Silver Acute 360」(尖锐之银360度)",
    "sakuya-100": "Close-up Magic",
    "sakuya-101": "Bounce No-bounce",
    "sakuya-102": "Magic Stars Sword",
    "sakuya-103": "Vanishing Everything",
    "sakuya-104": "Propelling Silver",
    "sakuya-105": "Square Ricochet",
    "sakuya-106": "离剑之见",
    "sakuya-107": "Perfect Maid",
    "sakuya-200": "幻符「杀人玩偶」",
    "sakuya-201": "时符「Private Square」(个人空间)",
    "sakuya-202": "伤符「Inscribe Red Soul」(铭刻于红魂)",
    "sakuya-203": "幻葬「夜雾幻影杀人鬼」",
    "sakuya-204": "「咲夜的世界」",
    "sakuya-205": "伤魂「Soul Sculpture」(灵魂雕塑)",
    "sakuya-207": "奇术「Eternal Meek」(永恒的温柔)",
    "sakuya-208": "速符「Luminous Ricochet」(闪光弹跳)",
    "alice-0": "步兵「Suicide Squad」(敢死小分队)",
    "alice-4": "剑符「Soldier of Cross」(交错的士兵)",
    "alice-8": "人偶「没有灵魂的民间舞」",
    "alice-100": "人偶操创",
    "alice-101": "人偶无操",
    "alice-102": "人偶置操",
    "alice-103": "人偶振起",
    "alice-104": "人偶归巢",
    "alice-105": "人偶火葬",
    "alice-106": "人偶千枪",
    "alice-107": "人偶SP",
    "alice-109": "大江户炸药机关人偶",
    "alice-111": "Seeker Wire",
    "alice-200": "魔符「Artful Sacrifice」(狡猾的献祭)",
    "alice-201": "战符「Little Legion」(小小军势)",
    "alice-202": "咒符「上海人偶」",
    "alice-203": "魔操「Return Inanimateness」(回归虚无)",
    "alice-204": "战操「Doll's War」(玩偶战争)",
    "alice-205": "诅咒「蓬莱人偶」",
    "alice-206": "侦符「Seeker Dolls」(探索人偶)",
    "alice-207": "红符「荷兰人偶」",
    "alice-208": "人偶「未来文乐」",
    "alice-209": "聚焦「Trip Wire」(绊线)",
    "patchouli-0": "火符「Akiba Summer」(秋叶之夏)",
    "patchouli-4": "水符「Jellyfish Princess」(水母公主)",
    "patchouli-8": "月金符「Sunshine Reflector」(日光反射器)",
    "patchouli-100": "Summer Red",
    "patchouli-101": "Winter Element",
    "patchouli-102": "Spring Wind",
    "patchouli-103": "Autumn Edge",
    "patchouli-104": "Doyou Spear",
    "patchouli-105": "Summer Flame",
    "patchouli-106": "Condensed Bubble",
    "patchouli-107": "Flash of Spring",
    "patchouli-108": "Autumn Blade",
    "patchouli-109": "Emerald City",
    "patchouli-200": "火金符「St. Elmo Pillar」(圣爱尔摩火柱)",
    "patchouli-201": "土水符「Noachian Deluge」(诺亚的大洪水)",
    "patchouli-202": "金木符「Elemental Harvester」(元素收获者)",
    "patchouli-203": "日符「Royal Flare」(皇家圣焰)",
    "patchouli-204": "月符「Silent Selene」(沉静的月神)",
    "patchouli-205": "火水木金土符「贤者之石」",
    "patchouli-207": "月木符「Satellite Himawari」(卫星向日葵)",
    "patchouli-210": "日木符「Photosynthesis」(光合作用)",
    "youmu-0": "人智剑「天女返」",
    "youmu-4": "樱花剑「闪闪散华」",
    "youmu-8": "断想剑「草木成佛斩」",
    "youmu-12": "瞑斩「楼观赋予我能斩断弹幕的心之眼」",
    "youmu-100": "反射下界斩",
    "youmu-101": "弦月斩",
    "youmu-102": "生死流转斩",
    "youmu-103": "凭依之缚",
    "youmu-104": "结跏跗斩",
    "youmu-105": "折伏无间",
    "youmu-106": "心抄斩",
    "youmu-107": "恶魂",
    "youmu-109": "炯眼剑",
    "youmu-111": "奇妙半身",
    "youmu-200": "人符「现世斩」",
    "youmu-201": "断命剑「冥想斩」",
    "youmu-202": "魂符「幽明的苦轮」",
    "youmu-203": "人鬼「未来永劫斩」",
    "youmu-204": "断迷剑「迷津慈航斩」",
    "youmu-205": "魂魄「幽明求闻持聪明之法」",
    "youmu-206": "剑伎「樱花闪闪」",
    "youmu-207": "断灵剑「成佛得脱斩」",
    "remilia-0": "命运「Miserable Fate」(悲惨的命运)",
    "remilia-4": "夜符「Bombard Night」(轰炸之夜)",
    "remilia-8": "蝙蝠「Vampire Sweep」(吸血鬼横扫)",
    "remilia-12": "神鬼「Remilia Stalker」(蕾米莉亚潜行者)",
    "remilia-100": "Demon Lord Walk",
    "remilia-101": "Servant Flyer",
    "remilia-102": "Demon Lord Cradle",
    "remilia-103": "Demon Lord Arrow",
    "remilia-104": "Vampire Claw",
    "remilia-105": "Chain Gang",
    "remilia-106": "Rocket Kick-up",
    "remilia-107": "Ceiling Fear",
    "remilia-109": "Demon's Dinner Fork",
    "remilia-200": "红符「红色不夜城」",
    "remilia-201": "必杀「Heart Break」(碎心)",
    "remilia-202": "夜符「Demon King Cradle」(恶魔之王的摇篮)",
    "remilia-203": "红魔「Scarlet Devil」(绯红色的恶魔)",
    "remilia-204": "神枪「Spear the Gungnir」(冈格尼尔之枪)",
    "remilia-205": "夜王「Dracula Cradle」(德古拉的摇篮)",
    "remilia-206": "夜符「Bad Lady Scramble」(恶女置乱)",
    "yuyuko-0": "幽符「冥界灵异点」",
    "yuyuko-4": "灵蝶「蝶之羽风暂留此世」",
    "yuyuko-8": "宴会「死后一切大团圆」",
    "yuyuko-100": "幽蝴蝶",
    "yuyuko-101": "未生之光",
    "yuyuko-102": "悉皆彷徨",
    "yuyuko-103": "蝴蝶梦之舞",
    "yuyuko-104": "好死之灵",
    "yuyuko-105": "凤蝶纹之枪",
    "yuyuko-106": "诱灵的甘蜜",
    "yuyuko-107": "逆转屏风",
    "yuyuko-108": "Sphere Bloom",
    "yuyuko-200": "死符「Ghastly Dream」(惊梦)",
    "yuyuko-201": "冥符「黄泉平坂行路」",
    "yuyuko-202": "灵符「无寿之梦」",
    "yuyuko-203": "死蝶「华胥的永眠」",
    "yuyuko-204": "再迷「幻想乡的黄泉归」",
    "yuyuko-205": "寿命「通向无寿国的期票」",
    "yuyuko-207": "蝶符「凤蝶纹的死枪」",
    "yuyuko-208": "幽雅「通向黄泉的诱蛾灯」",
    "yukari-0": "光弹「Doppler Effect」(多普勒效应)",
    "yukari-4": "捌器「将一切分成两个的东西」",
    "yukari-8": "幻巢「飞光虫之巢」",
    "yukari-12": "空饵「狂躁高速飞行物体」",
    "yukari-16": "「八云之巢」",
    "yukari-100": "后悔打开的玉匣",
    "yukari-101": "潜藏于禅寺的妖蝶",
    "yukari-102": "枕石漱流",
    "yukari-103": "幻想狂想穴",
    "yukari-104": "人间到处有青山",
    "yukari-105": "幻想卍伞",
    "yukari-106": "物质与反物质的宇宙",
    "yukari-107": "肉体分解机",
    "yukari-108": "魅惑的诱饵",
    "yukari-200": "境符「四重结界」",
    "yukari-201": "式神「八云蓝」",
    "yukari-202": "境符「二次元与三次元的境界」",
    "yukari-203": "结界「充满魅力的四重结界」",
    "yukari-204": "式神「橙」",
    "yukari-205": "结界「客观结界」",
    "yukari-207": "空饵「具有中毒性的诱饵」",
    "yukari-215": "废线「废弃车站下车之旅」",
    "suika-0": "吐息「小鬼的深呼吸」",
    "suika-4": "火弹「地灵活性弹」",
    "suika-8": "鬼神「Missing Purple Power」(遗失的高贵之力)",
    "suika-12": "鬼气「蒙蒙迷雾」",
    "suika-16": "「百万同一鬼」",
    "suika-100": "妖鬼-密-",
    "suika-101": "地灵-密-",
    "suika-102": "妖鬼-疏-",
    "suika-103": "萃鬼",
    "suika-104": "元鬼玉",
    "suika-105": "地灵-疏-",
    "suika-106": "厌雾",
    "suika-107": "疏鬼",
    "suika-109": "火鬼",
    "suika-200": "萃符「户隐山之投」",
    "suika-201": "醉神「鬼缚之术」",
    "suika-202": "鬼符「Missing Power」(遗失的力量)",
    "suika-203": "萃鬼「天手力男之投」",
    "suika-204": "醉梦「施饿鬼缚之术」",
    "suika-206": "雾符「云集雾散」",
    "suika-207": "鬼火「超高密度磷祸术」",
    "suika-208": "鬼符「大江山悉皆杀」",
    "reisen-0": "迫符「胁迫幻觉(Obsessioner)」",
    "reisen-4": "幻弹「幻想视差(Bluff Barrage)」",
    "reisen-8": "幻兔「平行交差(Parallel Cross)」",
    "reisen-100": "Mind Explosion",
    "reisen-101": "Illusionary Blast",
    "reisen-102": "Field Ultra Red",
    "reisen-103": "Disbelief Aspect",
    "reisen-104": "Mind Pending",
    "reisen-105": "Eyesight Cleaning",
    "reisen-106": "Field Ultra Violet",
    "reisen-107": "Disorder Eye",
    "reisen-108": "Mind Dropping",
    "reisen-109": "Ripple Vision",
    "reisen-110": "Under Sense Break",
    "reisen-200": "惑视「离圆花冠(Corolla Vision)」",
    "reisen-202": "幻爆「近眼花火(Mind Star Mine)」",
    "reisen-203": "幻惑「花冠视线(Crown Vision)」",
    "reisen-205": "「幻胧月睨(Lunatic Red Eyes)」",
    "reisen-206": "弱心「丧心丧意(Demotivation)」",
    "reisen-207": "丧心「丧心疮痍(Discarder)」",
    "reisen-208": "毒烟幕「瓦斯织物之玉」",
    "reisen-209": "生药「国士无双之药」",
    "aya-0": "突风「猿田彦的先导」",
    "aya-4": "旋符「飘妖扇」",
    "aya-8": "旋风「鸟居旋风」",
    "aya-12": "「幻想风靡」",
    "aya-100": "疾风扇",
    "aya-101": "疾走风靡",
    "aya-102": "天狗的立风露",
    "aya-103": "暗夜之砾",
    "aya-104": "烈风扇",
    "aya-105": "疾走优美",
    "aya-106": "天狗的下爆流",
    "aya-107": "镰风面纱",
    "aya-109": "天狗倒树",
    "aya-110": "天狗的太鼓",
    "aya-200": "旋符「红叶扇风」",
    "aya-201": "龙卷「天孙降临的道标」",
    "aya-202": "逆风「人间禁制之道」",
    "aya-203": "突符「天狗巨暴流」",
    "aya-205": "风符「天狗道的开风」",
    "aya-211": "魔兽「镰鼬面纱」",
    "komachi-0": "灵符「古老的地缚灵之复苏」",
    "komachi-4": "死符「区别死者的镰刀」",
    "komachi-8": "魂符「魂之游戏」",
    "komachi-100": "无惑而生的人灵",
    "komachi-101": "上天无路的地缚灵",
    "komachi-102": "脱魂的仪式",
    "komachi-103": "懒惰而生的浮游灵",
    "komachi-104": "死神的大镰",
    "komachi-105": "死出之风",
    "komachi-106": "无间之道",
    "komachi-107": "寂寞之人的紧缚灵",
    "komachi-108": "偶然路过的人灵",
    "komachi-110": "催命体验版",
    "komachi-200": "舟符「宛若河流般」",
    "komachi-201": "薄命「余命无几许」",
    "komachi-202": "灵符「到处都是的浮游灵」",
    "komachi-203": "死歌「八重雾中渡」",
    "komachi-204": "换命「不惜身命，可惜身命」",
    "komachi-205": "恨符「充满留恋的紧缚灵」",
    "komachi-211": "地狱「无间之狭间」",
    "iku-0": "光玉「闪光之龙眼」",
    "iku-4": "雷符「神鸣者的住处」",
    "iku-8": "棘符「雷云棘鱼」",
    "iku-12": "云界「玄云海的雷庭」",
    "iku-100": "龙鱼的一击",
    "iku-101": "羽衣若水",
    "iku-102": "龙鱼之怒",
    "iku-103": "静电诱导弹",
    "iku-104": "龙神的一击",
    "iku-105": "羽衣若风",
    "iku-106": "龙神之怒",
    "iku-107": "龙神的电光",
    "iku-111": "龙之眼",
    "iku-200": "电符「雷鼓弹」",
    "iku-201": "鱼符「龙鱼电钻」",
    "iku-202": "雷符「电气的龙宫」",
    "iku-203": "光星「光龙之叹息」",
    "iku-206": "雷鱼「雷云鱼游泳弹」",
    "iku-207": "羽衣「羽衣若空」",
    "iku-210": "龙鱼「龙宫使者的游泳弹」",
    "tenshi-0": "要石「天空之灵石」",
    "tenshi-4": "乾坤「粗暴的地母啊」",
    "tenshi-8": "灵想「镇守大地之石」",
    "tenshi-12": "天地「俯瞰世界的遥远的大地啊」",
    "tenshi-16": "「全人类的绯想天」",
    "tenshi-100": "坤仪之剑",
    "tenshi-101": "天罚的石柱",
    "tenshi-102": "非想的威光",
    "tenshi-103": "非想之剑",
    "tenshi-104": "六震-相-",
    "tenshi-105": "守护的要石",
    "tenshi-106": "天地之压",
    "tenshi-107": "绯想之剑",
    "tenshi-200": "地符「不让土壤之剑」",
    "tenshi-201": "非想「非想非非想之剑」",
    "tenshi-202": "天符「天道是非之剑」",
    "tenshi-203": "地震「先忧后乐之剑」",
    "tenshi-204": "气符「天启气象之剑」",
    "tenshi-205": "要石「天地开辟之挤压」",
    "tenshi-206": "气符「无念无想的境界」",
    "udonge-0": "迫符「胁迫幻觉(Obsessioner)」",
    "udonge-4": "幻弹「幻想视差(Bluff Barrage)」",
    "udonge-8": "幻兔「平行交叉(Parallel Cross)」",
    "udonge-100": "Mind Explosion",
    "udonge-101": "Illusionary Blast",
    "udonge-102": "Field Ultra Red",
    "udonge-103": "Disbelief Aspect",
    "udonge-104": "Mind Pending",
    "udonge-105": "Eyesight Cleaning",
    "udonge-106": "Field Ultra Violet",
    "udonge-107": "Disorder Eye",
    "udonge-108": "Mind Dropping",
    "udonge-109": "Ripple Vision",
    "udonge-110": "Under Sense Break",
    "udonge-200": "惑视「离圆花冠(Corolla Vision)」",
    "udonge-202": "幻爆「近眼花火(Mind Star Mine)」",
    "udonge-203": "幻惑「花冠视线(Crown Vision)」",
    "udonge-205": "「幻胧月睨(Lunatic Red Eyes)」",
    "udonge-206": "弱心「丧心丧意(Demotivation)」",
    "udonge-207": "丧心「丧心疮痍(Discarder)」",
    "udonge-208": "毒烟幕「瓦斯织物之玉」",
    "udonge-209": "生药「国士无双之药」",
    "marisa-219": "邪恋「容易结果的Master Spark」",
    "sakuya-206": "银符「Silver Bound」(银之跳跃)",
    "sakuya-209": "时符「咲夜特制秒表」",
    "patchouli-206": "水符「Jellyfish Princess」(水母公主)",
    "yuyuko-206": "灵蝶「蝶之羽风暂留此世」",
    "yukari-206": "幻巢「飞光虫之巢」",
    "suika-205": "鬼神「Missing Purple Power」(遗失的高贵之力)",
    "aya-206": "「幻想风靡」",
    "aya-212": "突风「猿田彦的先导」",
    "komachi-206": "死符「区别死者的镰刀」",
    "iku-209": "棘符「雷云棘鱼」",
    "tenshi-207": "「全人类的绯想天」",
    "remilia-207": "命运「Miserable Fate」(悲惨的命运)"
}