{
    "story-reimu-stage1-2-1": "星符「毫秒脉冲星」",
    "story-reimu-stage2-2-1": "拳符「愤怒的大云块」",
    "story-reimu-stage2-4-1": "入道「夏之幻想太郎」",
    "story-reimu-stage3-2-1": "皿投「土器回转投」",
    "story-reimu-stage3-4-1": "弓符「星龙弓」",
    "story-reimu-stage4-2-1": "杵符「金刚手菩萨的咒文」",
    "story-reimu-stage4-4-1": "超人「迦楼罗之翼」",
    "story-reimu-stage5-2-1": "「游戏到此为止了」",
    "story-reimu-stage6-2-1": "变化「满月的花鸟园」",
    "story-reimu-stage6-4-1": "变化「鸟兽戏画」",
    "story-reimu-stage6-6-1": "变化「百鬼妖界之门」",
    "story-reimu-stage7-2-1": "忧符「忧世之苦不绝如轮」",
    "story-reimu-stage7-4-1": "喜符「昂扬的神乐狮子」",
    "story-reimu-stage7-6-1": "怒符「愤怒的忌狼之面」",
    "story-reimu-stage7-8-1": "「Monkey Possession」（猿猴凭依）",
    "story-marisa-stage1-2-1": "御札「神社繁盛祈愿札」",
    "story-marisa-stage2-2-1": "水符「夏天的塑料瓶火箭」",
    "story-marisa-stage2-4-1": "妖怪战舰「三平战机」",
    "story-marisa-stage3-2-1": "本能「Freudian」（弗洛伊德学说）",
    "story-marisa-stage3-4-1": "茨符「Confined Innocent」（狭隘的天真）",
    "story-marisa-stage4-2-1": "德符「圣德的威望」",
    "story-marisa-stage4-4-1": "光符「无限条光芒」",
    "story-marisa-stage5-2-1": "「弁天的琵琶法师」",
    "story-marisa-stage6-2-1": "变化「满月的花鸟园」",
    "story-marisa-stage6-4-1": "变化「鸟兽戏画」",
    "story-marisa-stage6-6-1": "变化「百鬼妖界之门」",
    "story-marisa-stage7-2-1": "忧符「忧世之苦不绝如轮」",
    "story-marisa-stage7-4-1": "喜符「昂扬的神乐狮子」",
    "story-marisa-stage7-6-1": "怒符「愤怒的忌狼之面」",
    "story-marisa-stage7-8-1": "「Monkey Possession」（猿猴凭依）",
    "story-ichirin-stage1-2-1": "星符「毫秒脉冲星」",
    "story-ichirin-stage2-2-1": "御札「神社繁盛祈愿札」",
    "story-ichirin-stage2-4-1": "御札「梦幻的高速祈愿札」",
    "story-ichirin-stage3-2-1": "水符「夏天的塑料瓶火箭」",
    "story-ichirin-stage3-4-1": "妖怪战舰「三平战机」",
    "story-ichirin-stage4-2-1": "本能「Freudian」（弗洛伊德学说）",
    "story-ichirin-stage4-4-1": "茨符「Confined Innocent」（狭隘的天真）",
    "story-ichirin-stage5-2-1": "「弁天的琵琶法师」",
    "story-ichirin-stage6-2-1": "变化「满月的花鸟园」",
    "story-ichirin-stage6-4-1": "变化「鸟兽戏画」",
    "story-ichirin-stage6-6-1": "变化「百鬼妖界之门」",
    "story-ichirin-stage7-2-1": "忧符「忧世之苦不绝如轮」",
    "story-ichirin-stage7-4-1": "喜符「昂扬的神乐狮子」",
    "story-ichirin-stage7-6-1": "怒符「愤怒的忌狼之面」",
    "story-ichirin-stage7-8-1": "「Monkey Possession」（猿猴凭依）",
    "story-hijiri-stage1-2-1": "皿投「土器回转投」",
    "story-hijiri-stage2-2-1": "星符「毫秒脉冲星」",
    "story-hijiri-stage2-4-1": "魔符「Blaze Away」（连续射击）",
    "story-hijiri-stage3-2-1": "御札「神社繁盛祈愿札」",
    "story-hijiri-stage3-4-1": "御札「梦幻的高速祈愿札」",
    "story-hijiri-stage4-2-1": "德符「圣德的威望」",
    "story-hijiri-stage4-4-1": "光符「无限条光芒」",
    "story-hijiri-stage5-2-1": "「神社的佛祖大人」",
    "story-hijiri-stage6-2-1": "变化「满月的花鸟园」",
    "story-hijiri-stage6-4-1": "变化「鸟兽戏画」",
    "story-hijiri-stage6-6-1": "变化「百鬼妖界之门」",
    "story-hijiri-stage7-2-1": "忧符「忧世之苦不绝如轮」",
    "story-hijiri-stage7-4-1": "喜符「昂扬的神乐狮子」",
    "story-hijiri-stage7-6-1": "怒符「愤怒的忌狼之面」",
    "story-hijiri-stage7-8-1": "「Monkey Possession」（猿猴凭依）",
    "story-futo-stage1-2-1": "星符「毫秒脉冲星」",
    "story-futo-stage2-2-1": "本能「Freudian」（弗洛伊德学说）",
    "story-futo-stage2-4-1": "茨符「Confined Innocent」（狭隘的天真）",
    "story-futo-stage3-2-1": "拳符「愤怒的大云块」",
    "story-futo-stage3-4-1": "入道「夏之幻想太郎」",
    "story-futo-stage4-2-1": "水符「夏天的塑料瓶火箭」",
    "story-futo-stage4-4-1": "妖怪战舰「三平战机」",
    "story-futo-stage5-2-1": "「游戏到此为止了」",
    "story-futo-stage6-2-1": "变化「满月的花鸟园」",
    "story-futo-stage6-4-1": "变化「鸟兽戏画」",
    "story-futo-stage6-6-1": "变化「百鬼妖界之门」",
    "story-futo-stage7-2-1": "忧符「忧世之苦不绝如轮」",
    "story-futo-stage7-4-1": "喜符「昂扬的神乐狮子」",
    "story-futo-stage7-6-1": "怒符「愤怒的忌狼之面」",
    "story-futo-stage7-8-1": "「Monkey Possession」（猿猴凭依）",
    "story-miko-stage1-2-1": "御札「神社繁盛祈愿札」",
    "story-miko-stage2-2-1": "星符「毫秒脉冲星」",
    "story-miko-stage2-4-1": "魔符「Blaze Away」（连续射击）",
    "story-miko-stage3-2-1": "拳符「愤怒的大云块」",
    "story-miko-stage3-4-1": "入道「夏之幻想太郎」",
    "story-miko-stage4-2-1": "杵符「金刚手菩萨的咒文」",
    "story-miko-stage4-4-1": "超人「迦楼罗之翼」",
    "story-miko-stage5-2-1": "「游戏到此为止了」",
    "story-miko-stage6-2-1": "变化「满月的花鸟园」",
    "story-miko-stage6-4-1": "变化「鸟兽戏画」",
    "story-miko-stage6-6-1": "变化「百鬼妖界之门」",
    "story-miko-stage7-2-1": "忧符「忧世之苦不绝如轮」",
    "story-miko-stage7-4-1": "喜符「昂扬的神乐狮子」",
    "story-miko-stage7-6-1": "怒符「愤怒的忌狼之面」",
    "story-miko-stage7-8-1": "「Monkey Possession」（猿猴凭依）",
    "story-mamizou-stage1-2-1": "拳符「愤怒的大云块」",
    "story-mamizou-stage2-2-1": "皿投「土器回转投」",
    "story-mamizou-stage2-4-1": "弓符「星龙弓」",
    "story-mamizou-stage3-2-1": "杵符「金刚手菩萨的咒文」",
    "story-mamizou-stage3-4-1": "超人「迦楼罗之翼」",
    "story-mamizou-stage4-2-1": "德符「圣德的威望」",
    "story-mamizou-stage4-4-1": "光符「无限条光芒」",
    "story-mamizou-stage5-2-1": "御札「神社繁盛祈愿札」",
    "story-mamizou-stage5-4-1": "御札「梦幻的高速祈愿札」",
    "story-mamizou-stage5-6-1": "御札「对妖怪方位清除」",
    "story-mamizou-stage6-2-1": "忧符「忧世之苦不绝如轮」",
    "story-mamizou-stage6-4-1": "喜符「昂扬的神乐狮子」",
    "story-mamizou-stage6-6-1": "怒符「愤怒的忌狼之面」",
    "story-mamizou-stage6-8-1": "「Monkey Possession」（猿猴凭依）",
    "story-nitori-stage1-2-1": "杵符「金刚手菩萨的咒文」",
    "story-nitori-stage2-2-1": "拳符「愤怒的大云块」",
    "story-nitori-stage2-4-1": "入道「夏之幻想太郎」",
    "story-nitori-stage3-2-1": "星符「毫秒脉冲星」",
    "story-nitori-stage3-4-1": "魔符「Blaze Away」（连续射击）",
    "story-nitori-stage4-2-1": "御札「神社繁盛祈愿札」",
    "story-nitori-stage4-4-1": "御札「梦幻的高速祈愿札」",
    "story-nitori-stage5-2-1": "「游戏到此为止了」",
    "story-nitori-stage6-2-1": "变化「满月的花鸟园」",
    "story-nitori-stage6-4-1": "变化「鸟兽戏画」",
    "story-nitori-stage6-6-1": "变化「百鬼妖界之门」",
    "story-nitori-stage7-2-1": "忧符「忧世之苦不绝如轮」",
    "story-nitori-stage7-4-1": "喜符「昂扬的神乐狮子」",
    "story-nitori-stage7-6-1": "怒符「愤怒的忌狼之面」",
    "story-nitori-stage7-8-1": "「Monkey Possession」（猿猴凭依）",
    "story-koishi-stage1-2-1": "德符「圣德的威望」",
    "story-koishi-stage2-2-1": "皿投「土器回转投」",
    "story-koishi-stage2-4-1": "弓符「星龙弓」",
    "story-koishi-stage3-2-1": "星符「毫秒脉冲星」",
    "story-koishi-stage3-4-1": "魔符「Blaze Away」（连续射击）",
    "story-koishi-stage4-2-1": "拳符「愤怒的大云块」",
    "story-koishi-stage4-4-1": "入道「夏之幻想太郎」",
    "story-koishi-stage5-2-1": "「神社的佛祖大人」",
    "story-koishi-stage6-2-1": "变化「满月的花鸟园」",
    "story-koishi-stage6-4-1": "变化「鸟兽戏画」",
    "story-koishi-stage6-6-1": "变化「百鬼妖界之门」",
    "story-koishi-stage7-2-1": "忧符「忧世之苦不绝如轮」",
    "story-koishi-stage7-4-1": "喜符「昂扬的神乐狮子」",
    "story-koishi-stage7-6-1": "怒符「愤怒的忌狼之面」",
    "story-koishi-stage7-8-1": "「Monkey Possession」（猿猴凭依）",
    "story-kokoro-stage1-2-1": "拳符「愤怒的大云块」",
    "story-kokoro-stage2-2-1": "水符「夏天的塑料瓶火箭」",
    "story-kokoro-stage2-4-1": "妖怪战舰「三平战机」",
    "story-kokoro-stage3-2-1": "本能「Freudian」（弗洛伊德学说）",
    "story-kokoro-stage3-4-1": "茨符「Confined Innocent」（狭隘的天真）",
    "story-kokoro-stage4-2-1": "皿投「土器回转投」",
    "story-kokoro-stage4-4-1": "弓符「星龙弓」",
    "story-kokoro-stage5-2-1": "星符「毫秒脉冲星」",
    "story-kokoro-stage5-4-1": "魔符「Blaze Away」（连续射击）",
    "story-kokoro-stage6-2-1": "变化「满月的花鸟园」",
    "story-kokoro-stage6-4-1": "变化「鸟兽戏画」",
    "story-kokoro-stage6-6-1": "变化「百鬼妖界之门」",
    "story-kokoro-stage7-2-1": "「信仰心增加祈愿之仪」",
    "story-kokoro-stage7-4-1": "「二大宗教九字护身法」",
    "story-kokoro-stage7-6-1": "「面灵气大降服」",
    "story-kokoro-stage7-8-1": "「最后的三位一体宗教」",
    "player-reimu(0)-1": "妖怪破坏者",
    "player-reimu(0)-2": "即妙神域札",
    "player-reimu(0)-3": "空中升天脚",
    "player-reimu(0)-4": "亚空点穴",
    "player-reimu(0)-5": "阴阳弹",
    "player-reimu(0)-6": "前方安全札",
    "player-reimu(0)-7": "滞空三角跃",
    "player-reimu(0)-8": "灵符「梦想封印」",
    "player-reimu(0)-9": "宝具「阴阳飞鸟井」",
    "player-reimu(0)-10": "神技「八方龙杀阵」",
    "player-marisa(1)-1": "Witch Ley Line",
    "player-marisa(1)-2": "Rising Sweep",
    "player-marisa(1)-3": "Witching Blast",
    "player-marisa(1)-4": "Strato-Fraction",
    "player-marisa(1)-5": "Sweep Aside",
    "player-marisa(1)-6": "Powerful Drug",
    "player-marisa(1)-7": "Luminary Shot",
    "player-marisa(1)-8": "恋符「Master Spark」",
    "player-marisa(1)-9": "彗星「Blazing Star」",
    "player-marisa(1)-10": "星符「Satellite Illusion」",
    "player-ichirin(2)-1": "垂云的铁锤",
    "player-ichirin(2)-2": "一握的浮云",
    "player-ichirin(2)-3": "小小的神立云",
    "player-ichirin(2)-4": "愤怒的驰云",
    "player-ichirin(2)-5": "岭云的佛光",
    "player-ichirin(2)-6": "殴杀的流云",
    "player-ichirin(2)-7": "慈悲的北颪",
    "player-ichirin(2)-8": "岚符「佛罚的秋台风」",
    "player-ichirin(2)-9": "积乱「见越入道云」",
    "player-ichirin(2)-10": "拳固「忏悔的杀风」",
    "player-hijiri(3)-1": "哈奴曼之舞",
    "player-hijiri(3)-2": "广目天之眼",
    "player-hijiri(3)-3": "因陀罗之雷",
    "player-hijiri(3)-4": "韦驮天之脚",
    "player-hijiri(3)-5": "毗瑠璃之剑",
    "player-hijiri(3)-6": "迦楼罗之爪",
    "player-hijiri(3)-7": "难近母之魂",
    "player-hijiri(3)-8": "天符「三千大千世界之主」",
    "player-hijiri(3)-9": "天符「大日如来的光辉」",
    "player-hijiri(3)-10": "天符「释迦牟尼的五行山」",
    "player-futo(4)-1": "风之凶穴",
    "player-futo(4)-2": "贵龙之矢",
    "player-futo(4)-3": "抱水皿",
    "player-futo(4)-4": "天之磐舟",
    "player-futo(4)-5": "六壬神火",
    "player-futo(4)-6": "立向坐山",
    "player-futo(4)-7": "合局风",
    "player-futo(4)-8": "风符「三轮的皿风暴」",
    "player-futo(4)-9": "炎符「太乙真火」",
    "player-futo(4)-10": "运气「破局的开门」",
    "player-miko(5)-1": "缩地的披风",
    "player-miko(5)-2": "十七条光芒",
    "player-miko(5)-3": "探求欲望之魂",
    "player-miko(5)-4": "黄金之剑西潘戈",
    "player-miko(5)-5": "东方的影响力",
    "player-miko(5)-6": "十倍的垂听",
    "player-miko(5)-7": "闪耀者的慈雨",
    "player-miko(5)-8": "仙符「日出之处的道士」",
    "player-miko(5)-9": "道符「掌上的天道」",
    "player-miko(5)-10": "人符「劝善惩恶古之良典」",
    "player-nitori(6)-1": "空中冲击弹",
    "player-nitori(6)-2": "光子鱼雷",
    "player-nitori(6)-3": "再会橡胶圈",
    "player-nitori(6)-4": "罪恶齿轮",
    "player-nitori(6)-5": "水泡弹大回转",
    "player-nitori(6)-6": "菊一文字压缩机",
    "player-nitori(6)-7": "黄瓜音响系统",
    "player-nitori(6)-8": "暴雨「河底大战争」",
    "player-nitori(6)-9": "泡符「射击吧！泡泡龙」",
    "player-nitori(6)-10": "战机「飞翔吧！三平加油」",
    "player-koishi(7)-1": "Conditioned Teleport",
    "player-koishi(7)-2": "Fidgety Snatcher",
    "player-koishi(7)-3": "Growing Pain",
    "player-koishi(7)-4": "Catch and Rose",
    "player-koishi(7)-5": "Reflex Radar",
    "player-koishi(7)-6": "Stinging Mind",
    "player-koishi(7)-7": "Unanswered Love",
    "player-koishi(7)-8": "抑制「Super Ego」",
    "player-koishi(7)-9": "本能「本我的解放」",
    "player-koishi(7)-10": "梦符「先祖大人在看着你」",
    "player-mamizou(8)-1": "空蝉地藏变化",
    "player-mamizou(8)-2": "怪奇送行提灯",
    "player-mamizou(8)-3": "鸟兽琵琶法师",
    "player-mamizou(8)-4": "妖怪网切变化",
    "player-mamizou(8)-5": "妖怪唐伞变化",
    "player-mamizou(8)-6": "妖怪钓瓶变化",
    "player-mamizou(8)-7": "妖怪面影变化",
    "player-mamizou(8)-8": "变化「分福热水浴」",
    "player-mamizou(8)-9": "变化「百鬼妖界之门」",
    "player-mamizou(8)-10": "变化「二岩家的制裁」",
    "player-kokoro(9)-1": "吼怒的妖狐面",
    "player-kokoro(9)-2": "怒声的大蜘蛛面",
    "player-kokoro(9)-3": "忧叹的长壁面",
    "player-kokoro(9)-4": "忧心的鬼婆面",
    "player-kokoro(9)-5": "欢喜的狮子面",
    "player-kokoro(9)-6": "狂喜的火男面",
    "player-kokoro(9)-7": "心的轮盘",
    "player-kokoro(9)-8": "怒面「愤怒的忌狼之面」",
    "player-kokoro(9)-9": "凭依「喜怒哀乐附体」",
    "player-kokoro(9)-10": "忧面「杞人忧地」",
    "player-common(10)-1": "灵击札",
    "player-common(10)-2": "Magic Mushroom",
    "player-common(10)-3": "否德的法轮",
    "player-common(10)-4": "魔女的扫帚",
    "player-common(10)-5": "毘沙门天的宝塔",
    "player-common(10)-6": "仙风大皿",
    "player-common(10)-7": "很是威风的笏板",
    "player-common(10)-8": "Force shield",
    "player-common(10)-10": "随处可见的护身符",
    "player-common(10)-11": "仙人的装饰用佩剑",
    "player-common(10)-12": "揣在怀中的数珠",
    "player-common(10)-13": "天真无邪的帽子"
}