{
    "0": "灵符「阴阳印」",
    "1": "灵符「梦想封印」",
    "2": "灵符「博丽幻影」",
    "10": "魔符「Stardust」",
    "11": "魔符「Stardust Reverie」",
    "12": "魔符「Illusion Star」",
    "20": "时符「Private Vision」",
    "22": "时符「Mysterious Jack」",
    "30": "迷符「缠缚剑」",
    "32": "迷符「半身大悟」",
    "40": "波符「月面波纹(Luna Wave)」",
    "42": "散符「荣华之梦(Luna Megalopolis)」",
    "50": "冻符「Perfect Freeze」",
    "52": "冻符「Cold Divinity」",
    "60": "骚符「Soul Noise Flow」",
    "62": "骚符「Lyrica Solo Live」",
    "140": "骚符「Soul-Go-Happy」",
    "142": "骚符「Merlin Happy Live」",
    "150": "骚符「Noise Melancholy」",
    "152": "骚符「Lunasa Solo Live」",
    "70": "鸟符「Human Cage」",
    "71": "鸟符「Human Cage Double」",
    "72": "鸟符「Mysterious Song」",
    "80": "兔符「开运大纹」",
    "82": "兔符「因幡的白兔」",
    "100": "风符「风神一扇」",
    "102": "疾风「风神少女」",
    "110": "毒符「神经之毒」",
    "112": "毒符「忧郁之毒」",
    "90": "花符「幻想乡的开花」",
    "92": "幻想「花鸟风月，啸风弄月」",
    "120": "投钱「隔夜钱」",
    "122": "死神「Higan Retour」",
    "130": "罪符「彷徨的大罪」",
    "132": "审判「Last Judgement」"
}