{
    "th19_net_connected": "已成功连接到服务器",
    "th19_net_playername_1": "更改玩家的名称。",
    "th19_net_alphanumeric": "只能使用英文字母、数字和部分符号。",
    "th19_net_roomrename_1": "更改房间的名称。",
    "th19_net_roomrename_2": "请将该房间名告诉想一起玩的人。",
    "th19_net_room_joining": "正在尝试加入房间。",
    "th19_net_room_joined": "已加入房间。",
    "th19_net_waiting_for_opponent": "正在等待对战对手。",
    "th19_net_latency_none_notice": "和本地对战一样的操作感。适用于超高速网络连接",
    "th19_net_latency_none": "延迟设定：≪无延迟(no latency)≫",
    "th19_net_connection_failed": "连接失败",
    "th19_net_failed": "失败",
    "th19_net_try_again": "请稍后再次尝试",
    "th19_net_joined_p1": "找到了一位对手。您是1P（左侧）。",
    "th19_net_joined_p2": "找到了一位对手。您是2P（右侧）。",
    "th19_net_wait_for_p1": "等待1P操作中。",
    "th19_net_wait_for_p2": "等待2P操作中。",
    "th19_net_start": "请按确定按钮开始游戏。",
    "th19_net_change_delay": "您可以更改左侧和右侧的延迟设置。",
    "th19_net_latency_low": "延迟设定：≪低延迟(low latency)≫",
    "th19_net_latency_low_notice": "低延迟，适用于高速的网络连接",
    "th19_net_latency_mid": "延迟设定：≪中延迟(middle latency)≫",
    "th19_net_latency_mid_notice": "操作性差，适用于反应慢的网络连接",
    "th19_net_latency_high": "延迟设定：≪高延迟(high latency)≫",
    "th19_net_latency_high_notice": "勉强能玩的程度，适用于反应相当慢的网络连接"
}