{
    "0+Boss00BossCard1+0": "灵符「乱击阴阳玉」",
    "0+Boss00BossCard1H+0": "灵符「蹂躏阴阳玉」",
    "1+Boss00BossCard1+0": "星符「Shoot the Beast」(射兽)",
    "1+Boss00BossCard1H+0": "星符「Shoot the Beast King」(射向兽王)",
    "4+Boss00BossCard1+0": "陀螺「狛犬旋转」",
    "4+Boss00BossCard1+4": "陀螺「狛犬大回转」",
    "5+Boss00BossCard1+0": "宝石「Jewel Rain」(宝石雨)",
    "5+Boss00BossCard1+4": "宝石「Jewel Rain」(宝石雨)",
    "6+Boss00BossCard1+0": "弹符「Rabbit Shooting」(兔之射击)",
    "4+Boss00BossCard1H+0": "灵符「蹂躏阴阳玉」",
    "5+Boss00BossCard1H+0": "灵符「蹂躏阴阳玉」",
    "6+Boss00BossCard1H+0": "灵符「蹂躏阴阳玉」",
    "10+BossCard1+0": "龟符「龟甲地狱」",
    "10+BossCard2+0": "龟符「吉吊大结界」",
    "10+BossCard3+0": "龙符「龙纹弹」",
    "11+BossCard1+0": "天星马「Pegasus Cross」(天马十字)",
    "18+BossCard1+0": "「纯灵弹」",
    "18+BossCard2+0": "「无心纯灵弹」",
    "3+Boss00BossCard1H+0": "灵符「蹂躏阴阳玉」",
    "0+BossCard2+0": "「库存全部阴阳玉」",
    "0+BossCard3+0": "「降伏鬼畜生无须慈悲」",
    "2+Boss00BossCard1+0": "风符「Wind Rider」(乘风者)",
    "2+Boss00BossCard1+6": "风符「Wind Master」(御风者)",
    "3+Boss00BossCard1+0": "式神「Still-hunter Chen」(伏击猎人 橙)",
    "3+Boss00BossCard1+6": "式神「Multi Stillhunter」(多重伏击猎人)",
    "11+BossCard3+0": "「Last Shoot」(孤注一掷)",
    "12+BossCard2+0": "「Absorber Phantom」(汲取器幻影)",
    "12+BossCard3+0": "「底层的暴食」",
    "13+BossCard1+0": "鬼符「濛濛酒鬼」",
    "13+BossCard2+0": "鬼符「疏音濛濛酒鬼」",
    "13+BossCard3+0": "「美丽的地狱弹幕夜行」",
    "14+BossCard1+0": "猿击「Monkey Magic」(仙猴神通)",
    "15+BossCard1+0": "三头「Cerberus Fire」(刻耳柏洛斯之火)",
    "16+BossCard1+0": "咒血「Cursed Devil」(被诅咒的恶魔)",
    "17+BossCard1+0": "执行者「越狱跟踪狂」",
    "11+BossCard2+0": "天星马「Pegasus Starmine」(天马烟花)",
    "12+BossCard1+0": "宿怨「Gorge Riser」(胃袋勘探机)",
    "7+Boss00BossCard1+0": "死灵「Fairy of Dead」(死之妖精)",
    "8+BossCard1+0": "管狐「Cylinder Fox」(圆管之狐)",
    "9+BossCard1+0": "狸符「混入贪婪的动物灵中吧！」",
    "18+BossCard3+0": "「亡羊的王国」"
}