{
    "0": "尘符「Cosmic Dust」(宇宙灰尘)",
    "2": "尘符「宇宙尘埃」",
    "4": "尘符「唐柜翻转」",
    "6": "尘符「唐柜大翻转」",
    "8": "尘符「尘埃栖所」",
    "12": "魅符「不羁山涧之气」",
    "16": "魅符「梦呓森林之气」",
    "20": "魑符「狂暴山岳之气」",
    "14": "魅符「狂野山涧之气」",
    "18": "魅符「窒息森林之气」",
    "22": "魑符「暴怒山岳之气」",
    "24": "谜符「Pyramidal Labyrinth」(锥状迷宫)",
    "26": "谜符「Hexagonal Labyrinth」(六角迷宫)",
    "28": "塞符「Logical Wall」(逻辑高墙)",
    "30": "塞符「Logical Great Wall」(逻辑长城)",
    "32": "谜符「Ancient Trap」(古老陷阱)",
    "36": "金符「弹幕金字塔」",
    "40": "虚符「Streaming Doll」",
    "42": "虚符「Streaming Marionette」",
    "44": "群符「Rubble Data」",
    "46": "群符「Rubble Big Data」",
    "48": "「唯独射鹿的美丽记忆」",
    "52": "虚构「Discommunication」",
    "56": "宝珠「潮盈珠」",
    "60": "灾祸「山洪」",
    "62": "灾祸「长山洪」",
    "63": "灾祸「无尽山洪」",
    "64": "宝珠「潮干珠」",
    "68": "「Moon Dragon」",
    "72": "石神「成为岩石的碎石」",
    "76": "死符「永远之冬」",
    "78": "死符「恒久之冬」",
    "80": "生符「混沌之冬」",
    "84": "「弹幕的化石」",
    "88": "地符「幻想的遗骸」",
    "92": "月符「锦上的想象」",
    "96": "「Stone Goddess」",
    "98": "「不生不灭的石之女神」",
    "100": "鹿符「Deer Genocider」",
    "101": "蛇姬「Snakelander」",
    "102": "「Zoltax Communication」",
    "103": "真相「Tetra Mono-Eye」",
    "112": "「Angolmois的大王」",
    "104": "真相「Old Illuminati」",
    "105": "真相「Chemtrail Cloud」",
    "106": "真相「Reptilian Intelligence」",
    "107": "真相「Flat Earther」",
    "108": "真相「Artificial Disaster」",
    "109": "真相「New World Order」",
    "110": "真実「Tartarian Rhapsody」",
    "111": "「Chocolate River」"
}