{
    "Input Key": "键：",
    "Button 1": "Button1",
    "Button 2": "Button2",
    "Button 3": "Button3",
    "Button 4": "Button4",
    "Button 5": "Button5",
    "Button 6": "Button6",
    "Button 7": "Button7",
    "Button 8": "Button8",
    "Button 9": "Button9",
    "Button 10": "Button10",
    "Button 11": "Button11",
    "Button 12": "Button12",
    "Button 13": "Button13",
    "Button 14": "Button14",
    "Button 15": "Button15",
    "Button 16": "Button16",
    "Subtitle Unspecified": "※未设置※",
    "Subtitle Episode 2": "话",
    "Subtitle Unspecified 2": "※未设置※",
    "Config Choose Option": "选择",
    "Config Change Value": "切换",
    "Config OK": "确定",
    "Config Back": "返回",
    "Config Button Selection": "请按下要绑定的按键：↑(上)",
    "Config Keys": "\\C[255,0,0]任意按键：绑定按键　ESC：退出设置",
    "Config Graze": "按键1(擦弹) & 确定",
    "Config Attack": "按键2(攻击) & 取消",
    "Config Absorb": "按键3(吸收水)",
    "Ending 噴": "喷",
    "Ending 興": "兴",
    "Ending 頂": "顶",
    "Ending 無": "无",
    "Ending 減": "减",
    "Ending 戦": "战",
    "Ending 資": "资",
    "Ending 側": "侧",
    "Ending 気": "气",
    "Ending 強": "强",
    "Ending 貪": "贪",
    "Ending 貴": "贵",
    "Ending 異": "异",
    "Manual Switch page": "切换页面",
    "Manual Back": "返回",
    "th175_01": "被水淹没的沉愁地狱",
    "th175_02": "东方刚欲异闻",
    "th175_03": "天理人欲",
    "th175_04": "魔法使的忧郁",
    "th175_05": "昏暗的风穴",
    "th175_06": "漫游旧地狱街道",
    "th175_07": "业火地幔",
    "th175_08": "御柱的墓场",
    "th175_09": "大地之底，刚欲之海",
    "th175_10": "不朽的曼珠沙华",
    "th175_11": "魔法少女们的百年祭",
    "th175_12": "少女绮想曲",
    "th175_13": "恋色Master spark",
    "th175_14": "被封印的妖怪",
    "th175_15": "请注意万年备用伞",
    "th175_16": "Captain Murasa",
    "th175_17": "神圣庄严的古战场",
    "th175_18": "今宵是飘逸的利己主义者　～ Egoistic Flowers.",
    "th175_19": "大江山的花之酒宴",
    "th175_20": "灵知的太阳信仰",
    "th175_21": "Seraphic Chicken",
    "th175_22": "U.N.OWEN就是她吗？",
    "th16_14": "门再也进不去了",
    "th16_15": "秘神摩多罗",
    "th175_23": "贪欲之兽的记忆",
    "th175_24": "全有机体的记忆　～ Memory of Fossil Energy.",
    "MusicRoom 異": "异",
    "MusicRoom 愁": "愁",
    "MusicRoom 意": "意",
    "MusicRoom 飄": "飘",
    "MusicRoom 風": "风",
    "MusicRoom 太": "太",
    "MusicRoom 女": "女",
    "MusicRoom 機": "机",
    "MusicRoom 強": "强",
    "MusicRoom 想": "想",
    "MusicRoom 戦": "战",
    "MusicRoom 獄": "狱",
    "MusicRoom ？？？？？？？？？": "？？？？？？？？？",
    "MusicRoom AUTO": "※AUTO",
    "MusicRoom 選択": "选择",
    "MusicRoom 再生": "播放",
    "MusicRoom 停止": "停止",
    "MusicRoom 連続再生": "连续播放",
    "MusicRoom 終了": "结束",
    "/Functions/5/Literals/8": "选择",
    "/Functions/5/Literals/9": "确定",
    "/Functions/5/Literals/10": "返回",
    "Stage Result Proceed Button": "按键1: 前进",
    "Stage Result Give up prompt": [
        "要放弃吗？",
        "是的",
        "不要"
    ],
    "Stage Result Oil statistics": [
        "产油量",
        "吸收油量",
        "受害情况",
        "决斗用时",
        "合计用时",
        "",
        "本关得分",
        "合计得分"
    ],
    "Stage Result Blood statistics": [
        "产血量",
        "吸收血量",
        "受害情况",
        "决斗用时",
        "合计用时",
        "",
        "本关得分",
        "合计得分"
    ],
    "Stage Result Water statistics": [
        "产水量",
        "吸收水量",
        "受害情况",
        "决斗用时",
        "合计用时",
        "",
        "本关得分",
        "合计得分"
    ],
    "Stage Result Retry": "再战",
    "Stage Result Give up": "放弃",
    "Stage Result Proceed": "前进",
    "Stage Result Flawless Victory": [
        "完全胜利",
        ""
    ],
    "Stage Result Even Fight": [
        "旗鼓相当",
        ""
    ],
    "Stage Result Barely Survived": [
        "满身疮痍",
        ""
    ],
    "Stage Result Choose Option": "选择",
    "Stage Result Ok": "确定",
    "Stage Result Cancel": "取消",
    "Stage Result Give up prompt 2": [
        "要放弃吗？",
        "\\C[255,0,0]是的",
        "\\C[255,255,255]不要"
    ],
    "Stage Result Give up prompt 3": [
        "要放弃吗？",
        "是的",
        "\\C[255,0,0]不要"
    ],
    "Story Select Choose option": "选择",
    "Story Select Ok": "确定",
    "Story Select Back": "返回",
    "Story Select See records": "查看记录",
    "Story Select Choose Option 2": "选择",
    "Story Select Ok 2": "确定",
    "Story Select Cancel": "取消",
    "Story Select Tutorial": "操作练习",
    "Story Select Stage 1": "第一话",
    "Story Select Stage 2": "第二话",
    "Story Select Stage 3": "第三话",
    "Story Select Stage 4": "第四话",
    "Story Select Stage 5": "第五话",
    "Story Select Stage 6": "第六话",
    "Story Select Stage 7": "第七话",
    "Story Select A Long Day of Duels": "秘神与破坏神漫长的一天",
    "Story Select Epilogue": "尾声",
    "Story Select Greedy Trial": "刚欲的挑战",
    "Story Select Switch page": "切换页面",
    "Story Select Back 2": "返回",
    "Story Select Hign score": "最高得分",
    "Story Select Time to clear": "通关时间",
    "Story Select Attempts": "使用次数",
    "Story Select Surrenders": "疮痍放弃次数",
    "Story Select Clears": "通关次数",
    "Story Select Perfect clears": "{{ruby|完美|无伤}}通关次数",
    "th175_18_1": "今宵是飘逸的利己主义者　～ Egoistic Flowers.",
    "th175_24_1": "全有机体的记忆　～ Memory of Fossil Energy.",
    "Liquid Volume": "量",
    "Liquid Catch": "吸收的",
    "Battle Time": "决斗时间",
    "Score Bonus": "分数奖励",
    "Chanllenge Failed": "挑战失败",
    "Chanllenge Over": "挑战结束",
    "Appreciation": "鉴赏",
    "Stage Result Flawless Victory 2": "完全胜利",
    "Stage Result Even Fight 2": "旗鼓相当",
    "Stage Result Barely Survived 2": "满身疮痍",
    "Stage Result Give up prompt 4": "要放弃吗？",
    "Stage Result Give up prompt yes": "是的",
    "Stage Result Give up prompt no": "不要",
    "Story Select Stage 8": "第八话",
    "Story Select Gonyoku Chanllenge": "刚欲的挑战",
    "Config Graze Text": "擦弹",
    "Config Attack Text": "攻击",
    "Config Absorb Text": "吸水",
    "Config Complete": "结束",
    "Story Select Attempts 2": "使用次数",
    "Story Select Surrenders 2": "疮痍放弃次数",
    "Story Select Clears 2": "通关次数",
    "Story Select Perfect clears 2": "{{ruby|完美|无伤}}通关次数",
    "Hit Num": "击破数",
    "Chanllenge Level": "挑战关卡",
    "Spell Break": "击破符卡",
    "Create Water": "水量",
    "Catch Water": "吸收水量",
    "Total Damage": "受害状况",
    "Max Combo": "最大连击",
    "Total Time": "合计时间",
    "Item Obtained": "持有道具",
    "Total Score": "合计得分",
    "Play Times": "次",
    "Item Slot": "个",
    "BGM Get 1": "获得BGM「",
    "Trophy Get 1": "获得成就「",
    "Get 2": "」",
    "Release Gonyoku MODE": "MODE「刚欲的挑战」已被解锁",
    "Hint Close": "关闭",
    "Pause Choose Option": "选择",
    "Pause Ok": "确定",
    "Pause Back": "返回",
    "Config Button Selection 2": "请按下要绑定的按键："
}