{
    "reimu-1": "灵符「无理由的无差别降伏」",
    "reimu-2": "灵符「无理由的阴阳玉乱舞」",
    "reimu-3": "灵符「荒诞至极的无差别降伏」",
    "reimu-against-flandre": "石油「被污染的阴阳玉乱舞」",
    "marisa-1": "森符「Violent Tricholoma」",
    "kanako-2": "御柱「御柱摇曳弹」",
    "kanako-1": "风符「神地风暴」",
    "kanako-3": "御柱「Onbashira Bunker Buster」",
    "kanako-4-vs-minamitsu": "风符「船上水神风暴」",
    "kanako-5-vs-minamitsu": "御柱「船上御柱摇曳弹」",
    "kanako-6-vs-minamitsu": "御柱「Onbashira Torpedo」",
    "minamitsu-1": "风暴「Stormy Sailing」",
    "minamitsu-2": "沉没「贪欲亡者们的海域」",
    "minamitsu-3": "舟符「村纱船长的不幸出航」",
    "yorigamis-1": "石油「Flammable Rain」",
    "yorigamis-2": "石油「贫乏神式原油泄露污染」",
    "yorigamis-3": "油井「疫病神式天空挖掘机」",
    "flandre-1": "禁忌「Reckless Bullet」",
    "flandre-2": "禁忌「Cerberus Clipper」",
    "flandre-3": "「掌中的破坏者」",
    "yamame-1": "毒水「Unsanitary Rain」",
    "yamame-2": "毒蜘蛛「Venom Web」",
    "kogasa-1": "雨洞「Rainy Cave」",
    "kogasa-2": "水炮「Groundwater Stream」",
    "kogasa-against-minamitsu": "跳伞「大风暴惊喜」",
    "yuugi-1": "涌泉「热鬼挖掘击」",
    "yuugi-2": "怨泉「极乐温泉地狱」",
    "utsuho-1": "狱炎「Inferno Burner」",
    "utsuho-2": "狱光「Diffuse Hellfire」",
    "utsuho-3": "「盗日之鸦」",
    "utsuho-4": "狱炎「Magmatic Fall」",
    "kutaka-1": "长鸣「醒来吧，葬于此地的幽灵们」",
    "kutaka-2": "笛符「幽灵们啊，回归自己应属之地」",
    "kutaka-3": "庭渡「视野辽阔的旧地狱」",
    "kutaka-4": "庭渡「Algorithmic Phantom」",
    "yuuma-1": "采取「变革世界的黑水」",
    "yuuma-2": "蒸馏「简陋粗暴的蒸馏装置」",
    "yuuma-3": "刚欲「不应存在于此世的暴食」",
    "yuuma-4": "采血「盖亚的血液」",
    "yuuma-5": "精炼「被诅咒之血的追忆」",
    "yuuma-6": "「刚欲兽神饕餮的晚餐」",
    "yuuma-7-vs-flandre": "「肚子空空的贪婪怪兽」",
    "okina-1": "扉符「温泉游客的放松背影」",
    "okina-2": "扉符「太古之时失散的背影」",
    "okina-3": "扉符「罪人们的血腥背影」",
    "okina-4": "「被秘匿的时空幻想之旅」",
    "okina-5": "「秘而不宣的弹幕界之门」",
    "reimu-against-toutetsu": "「旧血池地狱暴力封锁」",
    "marisa-2": "火符「Violent Kaentake」",
    "yamame-3": "油水「Oil Burning Rain」",
    "yamame-4": "血蜘蛛「Impure Bloodly Web」"
}