{
    "th07 Menu Start": "开始游戏",
    "th07 Menu Extra Start": "开始Extra关卡的游戏",
    "th07 Menu Practice Start": "选择关卡开始练习",
    "th07 Menu Result": "浏览已取得的得分纪录和Spell Card列表",
    "th07 Menu Music Room": "欣赏音乐",
    "th07 Menu Replay": "欣赏游戏录像",
    "th07 Menu Option": "进行各种设定",
    "th07 Menu Quit": "差不多该休息了",
    "th07 Option Player": "更改初始残机数 （默认  3）",
    "th09 Menu Music Room": "进入音乐室",
    "th06 Bomb Reimu A": "灵符「梦想封印」",
    "th06 Bomb Reimu B": "梦符「封魔阵」",
    "th06 Bomb Marisa A": "魔符「Stardust Reverie」(星尘幻想)",
    "th06 Bomb Marisa B": "恋符「Master Spark」(极限火花)",
    "th07 Bomb Reimu A unfocused": "灵符「梦想封印 散」",
    "th07 Bomb Reimu A focused": "灵符「梦想封印 集」",
    "th07 Bomb Reimu B focused": "梦符「二重结界」",
    "th07 Bomb Marisa A focused": "魔符「Milky Way」(银河)",
    "th07 Bomb Marisa B unfocused": "恋符「Non-Directional Laser」(非定向光线)",
    "th07 Bomb Sakuya A unfocused": "幻符「Indiscriminate」(无差别伤害)",
    "th07 Bomb Sakuya A focused": "幻符「杀人玩偶」",
    "th07 Bomb Sakuya B unfocused": "时符「Perfect Square」(完美空间)",
    "th07 Bomb Sakuya B focused": "时符「Private Square」(个人空间)",
    "th08 Bomb Reimu": "灵符「梦想妙珠」",
    "th08 Bomb Reimu Last": "神灵「梦想封印　瞬」",
    "th08 Bomb Yukari": "境符「四重结界」",
    "th08 Bomb Yukari Last": "境界「永夜四重结界」",
    "th08 Bomb Marisa Last": "魔炮「Final Spark」(究极火花)",
    "th08 Bomb Alice": "魔符「Artful Sacrifice」(狡猾的献祭)",
    "th08 Bomb Alice Last": "魔操「Return Inanimateness」(回归虚无)",
    "th08 Bomb Sakuya Last": "幻葬「夜雾幻影杀人鬼」",
    "th08 Bomb Remilia": "红符「红色不夜城」",
    "th08 Bomb Remilia Last": "红魔「Scarlet Devil」(绯红色的恶魔)",
    "th08 Bomb Youmu": "人符「现世斩」",
    "th08 Bomb Youmu Last": "人鬼「未来永劫斩」",
    "th08 Bomb Yuyuko": "死符「Ghastly Dream」(惊梦)",
    "th08 Bomb Yuyuko Last": "死蝶「华胥的永眠」",
    "th08 Spell Dissolve": "「Dissolve Spell」(咏唱解除)",
    "th08 Spell Resurrection": "「Resurrection」(复活)",
    "th08 Music Room spoiler 1": "＊＊＊注意＊＊＊",
    "th08 Music Room spoiler 2": "　这首曲子还没有在游戏中播放过。",
    "th09 Music Room spoiler 1": "***** 注意 *****",
    "th09 Music Room spoiler 2": "选择的音乐尚未在游戏进行的过程中播放过。",
    "th10 Music Room spoiler 1": "<c$＊＊　选择的音乐尚未在游戏进行的过程中播放过　＊＊$>",
    "th10 Music Room spoiler 2": "<c$音乐的评论可能会造成剧透，$>",
    "th10 Music Room spoiler 3": "<c$即使那样也要播放吗？$>",
    "th10 Music Room spoiler 4": "<c$想现在就播放的话，请再次按下决定键。$>",
    "th10 Music Room spoiler 5": "<c$不想现在播放的话，请选择其它已开启的音乐进行欣赏。$>",
    "th13 spell nothing": "Nothing...",
    "th14 Dialog 640": "640×480",
    "th14 Dialog 960": "960×720",
    "th14 Dialog 1280": "1280×960 （推荐）",
    "th10 JP": "东方风神录",
    "alcostg JP": "黄昏酒场",
    "th11 JP": "东方地灵殿",
    "th12 JP": "东方星莲船",
    "th125 JP": "Double Spoiler",
    "th128 JP": "妖精大战争",
    "th13 JP": "东方神灵庙",
    "th14 JP": "东方辉针城",
    "th143 JP": "弹幕天邪鬼",
    "th15 JP": "东方绀珠传",
    "th06 config": "东方红魔乡　环境自定义程序",
    "th07 config": "东方妖妖梦　环境自定义程序",
    "th08 config": "东方永夜抄　环境自定义程序",
    "th09 config": "东方花映塚　环境自定义程序",
    "th095 config": "东方文花帖　环境自定义程序",
    "th10 config": "东方风神录　环境自定义程序",
    "alcostg config": "黄昏酒场　环境自定义程序",
    "th11 config": "东方地灵殿　环境自定义程序",
    "th12 config": "东方星莲船　环境自定义程序",
    "th125 config": "Double Spoiler ～ 东方文花帖　环境自定义程序",
    "th128 config": "妖精大战争　～ 东方三月精　环境自定义程序",
    "th13 config": "东方神灵庙　环境自定义程序",
    "th14 config": "东方辉针城　环境自定义程序",
    "th143 config": "弹幕天邪鬼　环境自定义程序",
    "th15 config": "东方绀珠传　环境自定义程序",
    "th06 up": "上 ",
    "th06 down": "下 ",
    "th06 left": "左 ",
    "th06 right": "右 ",
    "th06 vertex": "不使用顶点缓冲",
    "th06 fog": "不使用雾化效果",
    "th06 16bit textures": "仅使用16位贴图",
    "th06 Gouraud shading": "抑制Gouraud阴影处理的使用",
    "th06 color composition": "不合成贴图颜色",
    "th06 rasterizer mode": "启动 Reference Rasterizer 模式",
    "th06 clear buffer": "每次清除后台缓冲",
    "th06 depth test": "关闭色深测试",
    "th06 force frame": "强制运行在60FPS",
    "th06 fullscreen": "全屏幕模式",
    "th06 windowed": "窗口模式",
    "th06 full rate": "每次（通常）",
    "th06 half rate": "1/2 回",
    "th06 third rate": "1/3 回",
    "th06 32bits mode": "32位",
    "th06 16bits mode": "16位",
    "th06 accept": "确定",
    "th06 cancel": "取消",
    "th06 screen mode": "窗口风格",
    "th06 refresh rate": "绘制间隔",
    "th06 colors": "画面模式",
    "th06 pad X axis": "手柄左右游动速度(1～1000)",
    "th06 pad Y axis": "手柄上下游动速度(1～1000)",
    "th06 check pad": "手柄十字键确认",
    "th06 config saved caption": "确认",
    "th06 config saved text": "环境设置替换写入成功",
    "th07 16bits textures": "强制使用16Bits纹理",
    "th07 BGM memory": "从内存读取背景音乐",
    "th07 draw screen": "每次绘制画面",
    "th07 VSync": "不使用垂直同步",
    "th07 fullscreen": "全屏模式(推荐)",
    "th07 low effects": "最低",
    "th07 medium effects": "一般",
    "th07 high effects": "华丽(推荐)",
    "th07 32bits mode": "32位(推荐)",
    "th07 effect quality": "效果质量",
    "th08 fog": "不使用雾化效果（不推荐）",
    "th08 color composition": "不合成贴图颜色（禁止）",
    "th08 depth test": "关闭色深测试（不推荐）",
    "th08 rasterizer mode": "启动 Reference Rasterizer 模式（禁止）",
    "th08 VSync": "不使用垂直同步（不推荐）",
    "th09 full rate": "每次（推荐）",
    "th09 left side keyboard": "键盘左侧",
    "th09 right side keyboard": "键盘右侧",
    "th10 screen mode": "窗口模式",
    "th11 default": "返回默认设定",
    "th14 Dialog Fullscreen": "全屏启动",
    "th14 Dialog Always ask": "每次启动显示",
    "th10 Dialog Prompt": "请选择启动分辨率：",
    "th10 Dialog Fullscreen": "全屏幕模式",
    "th10 Dialog Always ask": "每次启动时询问",
    "th11 Dialog Fullscreen 640": "全屏模式(640×480)",
    "th11 Dialog Window 640": "窗口模式(640×480)",
    "th11 Dialog Window 960": "窗口模式(960×720)",
    "th11 Dialog Window 1280": "窗口模式(1280×960)",
    "th11 Dialog Game Start": "启动游戏",
    "th14 Dialog Prompt": "请选择启动分辨率：",
    "th143 Trophy Get": "的称号到手了",
    "th143 Trophy Format": "『%s』",
    "th165 JP": "秘封噩梦日记",
    "th11 input latency": "输入响应方式",
    "th11 stable input": "安定（通常情况无法顺利运行的情况）",
    "th11 normal input": "通常（CPU占用率较低）",
    "th11 automatic input": "自动（自动检测反应最快的模式）＊推荐",
    "th11 fast input": "高速（自动模式无法正常运行的情况）",
    "th11 input description": "设定「输入响应方式」可以调整按键的响应方式。\n「安定」和「通常」是前作使用的响应方式。\n「自动」会在硬件性能允许下做出最快的响应。\n「高速」可做到与「自动」同样的响应速度，但可能会造成部分画面错乱。\n＊以上设定仅在绘制间隔为「每回」的场合有效＊",
    "th11 always ask": "每次启动询问",
    "th11 sensitivity description": "上下左右移动不够灵敏时请降低灵敏值，觉得过于灵敏请增加灵敏值。\n（默认值：600）",
    "th11 joypad sensitivity": "手柄灵敏值",
    "th07 Option Graphic": "更改画面颜色数。32 Bit是最华丽的表示效果。",
    "th07 Option BGM": "更改BGM的播放格式。（默认  WAV）",
    "th07 Option Sound": "选择是否播放音效",
    "th07 Option Window Mode": "选择以窗口或全屏模式显示",
    "th07 Option Slow Mode": "当画面中存在大量子弹时故意拖慢处理。（无法记录得分/Replay）",
    "th07 Option Reset": "全部恢复默认设置",
    "th07 Option Key Config": "更改手柄的键位操作",
    "th07 Option Quit": "结束设置",
    "th07 Key Shot": "设置射击/确定按键",
    "th07 Key Bomb": "设置Bomb/取消按键",
    "th07 Key Slow": "设置低速移动按键",
    "th07 Key Skip": "设置对话跳过按键",
    "th07 Key Pause": "设置暂停按键",
    "th07 Key Up": "设置向上移动按键",
    "th07 Key Down": "设置向下移动按键",
    "th07 Key Left": "设置向左移动按键",
    "th07 Key Right": "设置向右移动按键",
    "th07 Key ShotSlow": "按住射击键时变为低速移动",
    "th07 Key Reset": "恢复默认设置",
    "th07 Key Quit": "退出按键设定",
    "th08 Option BGM Volume": "调整BGM音量",
    "th08 Option SE Volume": "调整效果音音量",
    "th08 Spell Practice Description": "Stage       取得/挑战可能/总数（括号内为全角色合计）",
    "th08 Spell Practice Percentages": "取得率　  （分角色／总计）",
    "th09 Menu Extra Start": "开始Extra模式的游戏",
    "th09 Menu Story Start": "开始花映塚模式的游戏",
    "th09 Menu Match Start": "开始对人、对CPU或观赏战斗的模式",
    "th09 Menu Replay": "播放Replay",
    "th09 Menu Result": "查看记录",
    "th09 Option BGM": "更改BGM的播放格式。＊现在还没有对应的MIDI格式",
    "th09 Option Key Config": "进行操作设定",
    "th09 Key Side": "选择1P或是2P的设定",
    "th09 Key Control Type": "PAD1,2：使用Pad　Full,Left,Right:使用键盘对应区域",
    "th09 Key Charge Type": "指定Charge键动作　Slow:低速移动、Charge:蓄力",
    "th09 Key Shot": "设置射击按键",
    "th09 Key Bomb": "设置Bomb按键",
    "th09 Key Slow": "设置低速或者蓄力按键",
    "th07 Spell Result Character Select": "%s  %3d枚中取得%3d枚（↓↑切换角色）",
    "th07 Stats ReimuA": "博丽灵梦 (灵)　",
    "th07 Stats ReimuB": "博丽灵梦 (梦)　",
    "th07 Stats MarisaA": "雾雨魔理沙 (魔)",
    "th07 Stats SakuyaA": "十六夜咲夜 (幻)",
    "th07 Stats MarisaB": "雾雨魔理沙 (恋)",
    "th07 Stats SakuyaB": "十六夜咲夜 (时)",
    "th07 Stats Total (All Characters)": "全主人公合计 　",
    "th07 Stats Time Since Startup": "总启动时间 %.2d:%.2d:%.2d",
    "th07 Stats Total Playtime": "总游戏时间 %.2d:%.2d:%.2d",
    "th07 Stats Play Count": "游戏回数",
    "th07 Stats Play Count +Phantasm": "游戏回数",
    "th07 Stats Clear Count": "通关回数　　　  　　　   %6d %6d %6d %6d %6d %6d",
    "th07 Stats Clear Count +Phantasm": "通关回数　　　   %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Continue": "续关回数　　　  　　　  %6d %6d %6d %6d %6d %6d",
    "th07 Stats Continue +Phantasm": "续关回数 　　　  %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Practice": "练习回数　　　  　　　  %6d %6d %6d %6d %6d %6d",
    "th07 Stats Practice +Phantasm": "练习回数 　　　  %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Retries": "Retry回数　　　 　　　 %6d %6d %6d %6d %6d %6d",
    "th07 Stats Retries +Phantasm": "Retry回数 　　　 %6d %6d %6d %6d %6d %6d %6d",
    "th08 Spell Result Character Select": "%3d/%3d（↓↑切换角色）",
    "th08 Stats Reimu & Yukari": "灵梦＆紫",
    "th08 Stats Marisa & Alice": "魔理沙＆爱丽丝",
    "th08 Stats Sakuya & Remilia": "咲夜＆蕾米莉亚",
    "th08 Stats Youmu & Yuyuko": "妖梦＆幽幽子",
    "th08 Stats Reimu": "博丽灵梦",
    "th08 Stats Yukari": "八云紫",
    "th08 Stats Marisa": "雾雨魔理沙",
    "th08 Stats Alice": "爱丽丝·M",
    "th08 Stats Sakuya": "十六夜咲夜",
    "th08 Stats Remilia": "蕾米莉亚·S",
    "th08 Stats Youmu": "魂魄妖梦",
    "th08 Stats Yuyuko": "西行寺幽幽子",
    "th08 Stats Total (All Characters)": "全主人公合计",
    "th08 Stats Time Since Startup": "总启动时间 %.2d:%.2d:%.2d",
    "th08 Stats Play Count": "游戏回数",
    "th08 Stats Total Playtime": "总游戏时间 %.2d:%.2d:%.2d",
    "th08 Stats Clear Count": "通关回数 %6d %6d %6d %6d %6d %6d",
    "th08 Stats Continue": "续关回数 %6d %6d %6d %6d %6d %6d",
    "th08 Stats Practice": "练习回数 %6d %6d %6d %6d %6d %6d",
    "th08 Spell Practice Easy Mode": "初月（Easy）",
    "th08 Spell Practice Normal Mode": "三日月（Normal）",
    "th08 Spell Practice Hard Mode": "上弦月（Hard）",
    "th08 Spell Practice Lunatic Mode": "待宵（Lunatic）",
    "th08 Spell Practice Extra Mode": "望月（Extra）",
    "th08 Spell Practice Last Word": "极意（Last Word）",
    "th08 Spell Practice List Description": "取得数/挑战数（括号内为通常游戏合计）",
    "th08 Spell Practice Highscore Title": "取得数/挑战数[最高分]　%s　全主人公合计",
    "th08 Spell Practice Comment": "符卡补足",
    "th08 Spell Condition Line 1 206": "解锁条件：普通模式下2角色以上Final B通关。",
    "th08 Spell Condition Line 2 206 207 209": "　　　　　　　难易度不限。",
    "th165 config": "秘封噩梦日记　环境自定义程序",
    "th09 save": "保存并退出",
    "th09 no save": "取消并退出",
    "th10 faith meter": "自机附近显示信仰槽",
    "th10 always ask": "每次启动询问",
    "th09 1P controller": "1P操作",
    "th09 2P controller": "2P操作",
    "th09 gamepad 1": "Gamepad 1",
    "th09 gamepad 2": "Gamepad 2",
    "th09 all keyboard": "键盘全部",
    "th06 minimum graphics": "不显示必要的最低限的残余物",
    "th16 config": "东方天空璋　环境自定义程序",
    "th10 slowshot": "按下射击键时保持低速移动",
    "DirectInput fix": "使用DirectInput",
    "DirectInput fix, layout-dependent shot key": "使用DirectInput (射击键: %c)",
    "th08 Music Room spoiler 3": "　如果在自己玩之前不想听、不想看说明的话，",
    "th08 Music Room spoiler 4": "　这种情况推荐赶快离开这个选单。",
    "th08 Music Room spoiler 6": "　（现在，在这里按下决定键，会和其他曲子一样播放，",
    "th08 Music Room spoiler 7": "　　并且一样显示出曲目评论，敬请注意。）",
    "th09 Music Room spoiler 3": "尽管可以提前聆听，但将不显示曲名以及评论。",
    "th07 Stats Header Easy": "Easy",
    "th07 Stats Header Normal": "Norm",
    "th07 Stats Header Hard": "Hard",
    "th07 Stats Header Lunatic": "Luna",
    "th07 Stats Header Extra": "Extra",
    "th07 Stats Header Phantasm": "Phants",
    "th07 Stats Header Total": "Total",
    "th06 Stats ReimuA": "博丽灵梦 (灵)　",
    "th06 Stats ReimuB": "博丽灵梦 (梦)　",
    "th06 Stats MarisaA": "雾雨魔理沙 (魔)",
    "th06 Stats MarisaB": "雾雨魔理沙 (恋)",
    "th17 Trophy Get": "的成就到手了",
    "th16 Dialog Fullscreen": "全屏幕模式",
    "th16 JP": "东方天空璋",
    "th17 JP": "东方鬼形兽",
    "th17 config": "东方鬼形兽 环境自定义程序",
    "th16 refresh rate": "绘制间隔",
    "th16 half rate": "1/2 回",
    "th16 third rate": "1/3 回",
    "th16 full rate": "每次（推荐）",
    "th16 no save": "取消并退出",
    "th16 slowshot": "按下射击键时保持低速移动",
    "th16 input latency": "输入响应方式",
    "th16 stable input": "安定（通常情况无法顺利运行的情况）",
    "th16 normal input": "通常（CPU占用率较低）",
    "th16 automatic input": "自动（自动检测反应最快的模式）＊推荐",
    "th16 fast input": "高速（自动模式无法正常运行的情况）",
    "th16 input description": "设定「输入响应方式」可以调整按键的响应方式。\n「安定」和「通常」是前作使用的响应方式。\n「自动」会在硬件性能允许下做出最快的响应。\n「高速」可做到与「自动」同样的响应速度，但可能会造成部分画面错乱。\n＊以上设定仅在绘制间隔为「每回」的场合有效＊",
    "th16 Dialog Always ask": "每次启动询问",
    "th16 sensitivity description": "上下左右移动不够灵敏时请降低灵敏值，觉得过于灵敏请增加灵敏值。\n（默认值：600）",
    "th16 joypad sensitivity": "手柄灵敏值",
    "th16 default": "返回默认设定",
    "th01": "东方灵异传　～ The Highly Responsive to Prayers",
    "th02": "东方封魔录　～ The Story of Eastern Wonderland",
    "th03": "东方梦时空　～ Phantasmagoria of Dim. Dream",
    "th04": "东方幻想乡　～ Lotus Land Story",
    "th05": "东方怪绮谈　～ Mystic Square",
    "th06": "东方红魔乡　～ the Embodiment of Scarlet Devil",
    "th07": "东方妖妖梦　～ Perfect Cherry Blossom",
    "th075": "东方萃梦想　～ Immaterial and Missing Power",
    "th08": "东方永夜抄　～ Imperishable Night",
    "th09": "东方花映塚　～ Phantasmagoria of Flower View",
    "th095": "东方文花帖　～ Shoot the Bullet",
    "th10": "东方风神录　～ Mountain of Faith",
    "alcostg": "黄昏酒场～Uwabami Breakers～",
    "th105": "东方绯想天　～ Scarlet Weather Rhapsody",
    "th11": "东方地灵殿　～ Subterranean Animism",
    "th12": "东方星莲船　～ Undefined Fantastic Object",
    "th123": "东方非想天则　～ 追寻特大型人偶之谜",
    "th125": "Double Spoiler　～ 东方文花帖",
    "th128": "妖精大战争　～ 东方三月精",
    "th13": "东方神灵庙　～ Ten Desires",
    "th135": "东方心绮楼　～ Hopeless Masquerade",
    "th14": "东方辉针城　～ Double Dealing Character",
    "th143": "弹幕天邪鬼　～ Impossible Spell Card",
    "th145": "东方深秘录　～ Urban Legend in Limbo",
    "th15": "东方绀珠传　～ Legacy of Lunatic Kingdom",
    "th155": "东方凭依华　～ Antinomy of Common Flowers",
    "th16": "东方天空璋　～ Hidden Star in Four Seasons",
    "th165": "秘封噩梦日记　～ Violet Detector",
    "th17": "东方鬼形兽 　～ Wily Beast and Weakest Creature",
    "nsml": "魔理沙和六个蘑菇 - New Super Marisa Land",
    "megamari": "MegaMari - 魔理沙的野望",
    "marilega": "MarisaLand Legacy",
    "th175": "东方刚欲异闻　～ 被水淹没的沉愁地狱",
    "th08 Menu Spell Practice": "与敌人进行符卡战斗",
    "th08 Spell Condition Line 1 205": "解锁条件：在望月（Extra）中收取7张以上的符卡",
    "th08 Spell Condition Line 2 205": "　　　　　　　Clear.",
    "th08 Spell Condition Line 1 207": "解锁条件：普通模式下3角色以上Final B通关。",
    "th08 Spell Condition Line 1 208": "解锁条件：符卡练习模式下收取50张以上的符卡",
    "th08 Spell Condition Line 2 208 211 217 220": "　　　　　　　全角色合计。",
    "th08 Spell Condition Line 1 209": "解锁条件：普通模式下4角色以上Final B通关。",
    "th08 Spell Condition Line 1 210": "解锁条件：收取No.%.3d号符卡。",
    "th08 Spell Condition Line 1 211": "解锁条件：符卡练习模式下收取15张以上的LSC",
    "th08 Spell Condition Line 1 212": "解锁条件：收取No.%.3d,%.3d号符卡",
    "th08 Spell Condition Line 2 212": "　　　　　　　并且，挑战一次No.%.3d号符卡",
    "th08 Spell Condition Line 1 213": "解锁条件：挑战一次No.%.3d,%.3d,%.3d号符卡",
    "th08 Spell Condition Line 2 213 214 222": "　　　　　　　不一定要收取。",
    "th08 Spell Condition Line 1 214": "解锁条件：挑战一次No.%.3d,%.3d,%.3d,%.3d号符卡",
    "th08 Spell Condition Line 1 215": "解锁条件：使用单魔理沙机体将三日月（Normal）难度下的",
    "th08 Spell Condition Line 2 215": "　　　　　　　符卡全部收取。",
    "th08 Spell Condition Line 2 216": "　　　　　　　仅限FinalB线路。",
    "th08 Spell Condition Line 1 217": "解锁条件：符卡练习模式下收取120张以上的符卡",
    "th08 Spell Condition Line 1 218": "解锁条件：普通模式下6角色以上Final B通关。",
    "th08 Spell Condition Line 1 219": "解锁条件：3角色以上望月（Extra）通关。",
    "th08 Spell Condition Line 1 220": "解锁条件：符卡练习模式下收取30张以上的LSC",
    "th08 Spell Condition Line 1 221": "解锁条件：待宵（Lunatic）难度下通关。",
    "th08 Spell Condition Line 2 221": "　　　　　　　可续关，使用角色不限。",
    "th08 Spell Condition Line 1 216": "解锁条件：使用单灵梦机体通关上弦月（Hard）以上难度。",
    "th08 Spell Condition Line 1 222": "解锁条件：此外的Last Word都挑战一次。",
    "th105_init_failed": "初始化失败",
    "th105_replay_return_to_select": "即将返回选单，要保存replay吗？",
    "th105_replay_return_to_title": "即将返回标题画面，要保存replay吗？",
    "th105_replay_saved": "已保存replay",
    "th105_replay_save": "要保存Replay吗？",
    "th105_replay_delete": "要删除吗？",
    "th105_continue": "要继续吗？还有%d回",
    "th105_netplay_select_addr": "请选择连接",
    "th105_netplay_port": "请输入端口号",
    "th105_netplay_enter_addr": "请输入连接地址",
    "th105_netplay_allow_spectating": "允许观战吗？",
    "th105_netplay_await": "连接等待中",
    "th105_netplay_no_spectating": "不允许观战",
    "th105_netplay_game_not_available": "对战尚未开始",
    "th105_netplay_connection_failed": "连接失败",
    "th105_netplay_connecting": "连接中",
    "th105_netplay_connect_for_match": "要进行对战吗？",
    "th105_netplay_confirm_address": "连接",
    "th105_netplay_already_playing": "已在对战中",
    "th105_netplay_already_playing_spectate": "已在对战中 要观战吗？",
    "th105_delete_failed": "删除失败",
    "th105_profile_save_changes": "要保存编辑内容吗？",
    "th105_profile_creation_failed": "创建失败",
    "th105_profile_created": "已创建",
    "th105_profile_copied": "已复制",
    "th105_profile_copy_failed": "复制失败",
    "th105_profil_rename_failed": "名称变更失败",
    "th105_profil_renamed": "名称已变更",
    "th123_replay_create_folder_failed": "replay文件夹生成失败",
    "th123_profile_create_folder_failed": "profile文件夹生成失败",
    "th105_delete_suceeded": "已删除",
    "th08 Spell Practice Last Spell": "Last",
    "th08 Spell Practice Owner/Difficulty Line": "使用者  %s　　%s %s",
    "th18": "东方虹龙洞　～ Unconnected Marketeers",
    "th18 card unobtained": "还未获取",
    "th18 card unavailable": "体验版无法获取",
    "th18 Trophy Get": "的成就到手了",
    "th18 Trophy Get Legacy": "成就获取成功！",
    "th07 DirectInput": "手柄输入不使用DirectInput",
    "th18 Ability Unlock": "获取成功！",
    "th18 JP": "东方虹龙洞",
    "th18 config": "东方虹龙洞 环境自定义程序",
    "th16 save": "保存并退出",
    "th08 Music Room spoiler 5": "　",
    "th08 Spell Condition Line 2 218": "　　　　　　　",
    "th06 DirectInput": "不使用DirectInput手柄",
    "th18 screen mode": "画面分辨率",
    "th18 Dialog Borderless DOT": "无边框窗口 DOT by DOT（推荐）",
    "th18 Dialog Borderless": "无边框窗口 最大显示",
    "th18 Dialog Fullscreen 1280": "全屏 1280×960",
    "th18 Dialog Fullscreen 960": "全屏  960×720",
    "th18 Dialog Fullscreen 640": "全屏  640×480",
    "th18 Dialog Window 2560": "窗口    2560×1920",
    "th18 Dialog Window 1920": "窗口    1920×1440",
    "th18 Dialog Window 1280": "窗口    1280×960",
    "th18 Dialog Window 960": "窗口    960×720",
    "th18 Dialog Window 640": "窗口    640×480",
    "th105_profile_deck_too_big": "卡组中不是20张卡牌",
    "th105_profile_overwrite": "可以覆盖吗？",
    "th105_profile_will_copy": "可以复制吗？",
    "th105_profile_will_delete": "可以删除吗？",
    "th06 BGM In-game format": "♪%s",
    "th07 Supernatural Border": "Supernatural Border!!",
    "th07 CherryPoint Max": "CherryPoint Max!",
    "th07 Border Bonus Format": "Border Bonus %7d"
}