{
    "player-reimu(0)-1": "灵符「梦想封印」",
    "player-reimu(0)-2": "神技「八方龙杀阵」",
    "player-reimu(0)-3": "宝具「阴阳飞鸟井」",
    "story-reimu-stage1-2-1": "星符「Occultation」(掩星)",
    "story-reimu-stage1-3-1": "＊被诅咒的历代校长的肖像＊",
    "story-reimu-stage2-2-1": "雷符「低速的务光」",
    "story-reimu-stage2-3-1": "＊到死都会实现愿望的猴爪＊",
    "player-marisa(1)-1": "恋符「Master Spark」\n　　（极限火花）",
    "player-marisa(1)-2": "彗星「Blazing Star」\n　　（闪亮之星）",
    "player-marisa(1)-3": "星符「Satellite Illusion」\n　　（卫星幻觉）",
    "player-kasen(10)-1": "包符「假肢变形」",
    "player-kasen(10)-2": "龙符「Dragon's Growl」\n　　（巨龙之啸）",
    "player-kasen(10)-3": "鹰符「Hawk Beacon」\n　　（飞鹰信标）",
    "player-ichirin(2)-1": "岚符「佛罚的秋台风」",
    "player-ichirin(2)-2": "积乱「见越入道云」",
    "player-ichirin(2)-3": "拳固「忏悔的杀风」",
    "player-hijiri(3)-1": "天符「三千大千世界之主」",
    "player-hijiri(3)-2": "天符「大日如来的光辉」",
    "player-hijiri(3)-3": "天符「释迦牟尼的五行山」",
    "player-futo(4)-1": "风符「三轮的皿风暴」",
    "player-futo(4)-2": "炎符「太乙真火」",
    "player-futo(4)-3": "运气「破局的开门」",
    "player-miko(5)-1": "仙符「日出之处的道士」",
    "player-miko(5)-2": "道符「掌上的天道」",
    "player-miko(5)-3": "人符「劝善惩恶古之良典」",
    "player-mamizou(8)-1": "变化「分福热水浴」",
    "player-mamizou(8)-2": "变化「百鬼妖界之门」",
    "player-mamizou(8)-3": "变化「二岩家的制裁」",
    "player-mokou(11)-1": "焰符「自灭火焰大旋风」",
    "player-mokou(11)-2": "不死「凯风快晴飞翔蹴」",
    "player-mokou(11)-3": "咒札「无差别放火之符」",
    "player-sinmyoumaru(12)-1": "小槌「传说中的大宴席」",
    "player-sinmyoumaru(12)-2": "小人「一寸法师亦有五分之魂」",
    "player-sinmyoumaru(12)-3": "钓符「可爱的太公望」",
    "player-nitori(6)-1": "暴雨「河底大战争」",
    "player-nitori(6)-2": "泡符「射击吧！泡泡龙」",
    "player-nitori(6)-3": "战机「飞翔吧！三平加油」",
    "player-koishi(7)-1": "抑制「Super Ego」\n　　（超我）",
    "player-koishi(7)-2": "本能「本我的解放」",
    "player-koishi(7)-3": "梦符「先祖大人在看着你」",
    "player-kokoro(9)-1": "怒面「愤怒的忌狼之面」",
    "player-kokoro(9)-2": "凭依「喜怒哀乐附体」",
    "player-kokoro(9)-3": "忧面「杞人忧地」",
    "player-usami(13)-1": "枪符「3D Printer Gun」\n　　（3D打印枪）",
    "player-usami(13)-2": "念力「Psychokinesis APP」\n　　（念力应用）",
    "player-usami(13)-3": "念力「Telekinesis 通信塔」\n　　（隔空移物　通信塔）",
    "story-marisa-stage1-2-1": "结界「人至之处的青山」",
    "story-marisa-stage2-2-1": "恶符「八丈高的灵异柱」",
    "story-marisa-stage3-1-1": "＊被诅咒的响一声电话＊",
    "story-marisa-stage4-2-1": "雷符「低速的务光」",
    "story-marisa-stage4-3-1": "＊到死都会实现愿望的猴爪＊",
    "story-marisa-stage4-4-1": "＊猿之手会做一个神秘的梦＊",
    "story-marisa-stage5-2-1": "念力「Psycho Plosion」(精神爆发)",
    "story-marisa-stage5-3-1": "念力「Telekinesis 非法投掷物」",
    "story-marisa-stage5-4-1": "＊现世的神秘主义者＊",
    "story-kasen-stage1-2-1": "结界「人至之处的青山」",
    "story-kasen-stage2-2-1": "皿符「自暴自弃的阿菊」",
    "story-kasen-stage3-1-1": "＊裂口的感情＊",
    "story-kasen-stage4-2-1": "未确认「幽浮戏画」",
    "story-kasen-stage4-3-1": "＊满员的外星人球＊",
    "story-kasen-stage5-2-1": "念力「Psycho Plosion」(精神爆发)",
    "story-kasen-stage5-3-1": "念力「Telekinesis 非法投掷物」",
    "story-kasen-stage5-4-1": "＊现世的神秘主义者＊",
    "story-ichirin-stage1-2-1": "皿符「自暴自弃的阿菊」",
    "story-ichirin-stage2-2-1": "星符「Occultation」(掩星)",
    "story-ichirin-stage3-2-1": "大渔「空中大回转钓鱼法」",
    "story-ichirin-stage3-3-1": "＊幻之国不来夫斯库＊",
    "story-ichirin-stage4-2-1": "怪人「Hermetic Manteau」(神秘披风)",
    "story-ichirin-stage4-3-1": "＊大怪人的动脉与静脉＊",
    "story-ichirin-stage4-4-1": "＊世纪的怪人红披风蓝披风＊",
    "story-hijiri-stage1-2-1": "恶符「八丈高的灵异柱」",
    "story-hijiri-stage2-2-1": "皿符「自暴自弃的阿菊」",
    "story-hijiri-stage3-1-1": "＊尼西的完全养殖技术＊",
    "story-hijiri-stage4-2-1": "炎符「不死鸟的超高温羽毛」",
    "story-hijiri-stage4-3-1": "＊凯风晴天快晴脚＊",
    "story-hijiri-stage5-2-1": "怪人「Hermetic Manteau」(神秘披风)",
    "story-hijiri-stage5-3-1": "＊大怪人的动脉与静脉＊",
    "story-hijiri-stage5-4-1": "＊世纪的怪人红披风蓝披风＊",
    "story-futo-stage1-2-1": "恶符「八丈高的灵异柱」",
    "story-futo-stage2-2-1": "结界「人至之处的青山」",
    "story-futo-stage3-2-1": "炎符「不死鸟的超高温羽毛」",
    "story-futo-stage3-3-1": "＊凯风晴天快晴脚＊",
    "story-futo-stage4-2-1": "超音速「老妇人的冲刺」",
    "story-futo-stage4-3-1": "＊高速路涡轮空中转向＊",
    "story-futo-stage4-4-1": "＊涡轮老太婆走死走爱＊",
    "story-miko-stage1-2-1": "皿符「自暴自弃的阿菊」",
    "story-miko-stage2-2-1": "恶符「八丈高的灵异柱」",
    "story-miko-stage3-1-1": "＊尼西的完全养殖技术＊",
    "story-miko-stage4-2-1": "大渔「空中大回转钓鱼法」",
    "story-miko-stage4-3-1": "＊幻之国不来夫斯库＊",
    "story-miko-stage5-2-1": "超音速「老妇人的冲刺」",
    "story-miko-stage5-3-1": "＊高速路涡轮空中转向＊",
    "story-miko-stage5-4-1": "＊涡轮老太婆走死走爱＊",
    "story-mamizou-stage1-2-1": "星符「Occultation」(掩星)",
    "story-mamizou-stage2-2-1": "结界「人至之处的青山」",
    "story-mamizou-stage3-1-1": "＊裂口的感情＊",
    "story-mamizou-stage4-2-1": "雷符「低速的务光」",
    "story-mamizou-stage4-3-1": "＊到死都会实现愿望的猴爪＊",
    "story-mamizou-stage4-4-1": "＊猿之手会做一个神秘的梦＊",
    "story-mamizou-stage5-2-1": "念力「Psycho Plosion」(精神爆发)",
    "story-mamizou-stage5-3-1": "念力「Telekinesis 非法投掷物」",
    "story-mamizou-stage5-4-1": "＊现世的神秘主义者＊",
    "story-mokou-stage1-2-1": "结界「人至之处的青山」",
    "story-mokou-stage2-2-1": "星符「Occultation」(掩星)",
    "story-mokou-stage3-1-1": "＊尼西的完全养殖技术＊",
    "story-mokou-stage4-2-1": "雷符「低速的务光」",
    "story-mokou-stage4-3-1": "＊到死都会实现愿望的猴爪＊",
    "story-mokou-stage5-2-1": "念力「Psycho Plosion」(精神爆发)",
    "story-mokou-stage4-4-1": "＊猿之手会做一个神秘的梦＊",
    "story-mokou-stage5-3-1": "念力「Telekinesis 非法投掷物」",
    "story-mokou-stage5-4-1": "＊现世的神秘主义者＊",
    "story-sinmyoumaru-stage1-2-1": "恶符「八丈高的灵异柱」",
    "story-sinmyoumaru-stage2-2-1": "皿符「自暴自弃的阿菊」",
    "story-sinmyoumaru-stage3-1-1": "＊被诅咒的响一声电话＊",
    "story-sinmyoumaru-stage4-2-1": "未确认「幽浮戏画」",
    "story-sinmyoumaru-stage4-3-1": "＊满员的外星人球＊",
    "story-sinmyoumaru-stage4-4-1": "＊差不多该回家了外星人们啊＊",
    "story-sinmyoumaru-stage5-2-1": "念力「Psycho Plosion」(精神爆发)",
    "story-sinmyoumaru-stage5-3-1": "念力「Telekinesis 非法投掷物」",
    "story-sinmyoumaru-stage5-4-1": "＊现世的神秘主义者＊",
    "story-nitori-stage1-2-1": "星符「Occultation」(掩星)",
    "story-nitori-stage2-2-1": "恶符「八丈高的灵异柱」",
    "story-nitori-stage3-2-1": "炎符「不死鸟的超高温羽毛」",
    "story-nitori-stage3-3-1": "＊凯风晴天快晴脚＊",
    "story-nitori-stage4-2-1": "未确认「幽浮戏画」",
    "story-nitori-stage4-3-1": "＊满员的外星人球＊",
    "story-nitori-stage4-4-1": "＊差不多该回家了外星人们啊＊",
    "story-koishi-stage1-2-1": "结界「人至之处的青山」",
    "story-koishi-stage2-2-1": "星符「Occultation」(掩星)",
    "story-koishi-stage3-2-1": "雷符「低速的务光」",
    "story-koishi-stage3-3-1": "＊到死都会实现愿望的猴爪＊",
    "story-koishi-stage3-4-1": "＊猿之手会做一个神秘的梦＊",
    "story-koishi-stage4-2-1": "念力「Psycho Plosion」(精神爆发)",
    "story-koishi-stage4-3-1": "念力「Telekinesis 非法投掷物」",
    "story-koishi-stage4-4-1": "＊现世的神秘主义者＊",
    "story-kokoro-stage1-2-1": "恶符「八丈高的灵异柱」",
    "story-kokoro-stage2-1-1": "＊尼西的完全养殖技术＊",
    "story-kokoro-stage3-2-1": "皿符「自暴自弃的阿菊」",
    "story-kokoro-stage3-3-1": "＊从晦暗的古井底＊",
    "story-kokoro-stage4-2-1": "怪人「Hermetic Manteau」(神秘披风)",
    "story-kokoro-stage4-3-1": "＊大怪人的动脉与静脉＊",
    "story-kokoro-stage4-4-1": "＊世纪的怪人红披风蓝披风＊",
    "story-usami-stage1-2-1": "雷符「低速的务光」",
    "story-usami-stage1-3-1": "＊到死都会实现愿望的猴爪＊",
    "story-usami-stage1-4-1": "＊猿之手会做一个神秘的梦＊",
    "story-usami-stage2-2-1": "恶符「八丈高的灵异柱」",
    "story-usami-stage2-3-1": "＊被谜之女子囚禁的仲夏之夜＊",
    "story-usami-stage3-1-1": "＊裂口的感情＊",
    "story-usami-stage4-2-1": "星符「Occultation」(掩星)",
    "story-usami-stage4-3-1": "＊被诅咒的历代校长的肖像＊",
    "story-usami-stage4-4-1": "＊夜间学校怪谈云游＊",
    "story-usami-stage5-2-1": "大渔「空中大回转钓鱼法」",
    "story-usami-stage5-3-1": "＊幻之国不来夫斯库＊",
    "story-usami-stage6-2-1": "炎符「不死鸟的超高温羽毛」",
    "story-usami-stage6-3-1": "＊凯风晴天快晴脚＊",
    "story-usami-stage7-2-1": "怪人「Hermetic Manteau」(神秘披风)",
    "story-usami-stage7-3-1": "＊大怪人的动脉与静脉＊",
    "story-usami-stage7-4-1": "＊世纪的怪人红披风蓝披风＊",
    "story-reimuB-stage1-2-1": "未确认「幽浮戏画」",
    "story-reimuB-stage1-3-1": "＊满员的外星人球＊",
    "story-reimuB-stage1-4-1": "＊差不多该回家了外星人们啊＊",
    "story-reimuB-stage2-2-1": "炎符「不死鸟的超高温羽毛」",
    "story-reimuB-stage2-3-1": "＊凯风晴天快晴脚＊",
    "story-reimuB-stage3-2-1": "雷符「低速的务光」",
    "story-reimuB-stage3-3-1": "＊到死都会实现愿望的猴爪＊",
    "story-reimuB-stage3-4-1": "＊猿之手会做一个神秘的梦＊",
    "story-reimuB-stage4-2-1": "念力「Psycho Plosion」(精神爆发)",
    "story-reimuB-stage4-3-1": "念力「Telekinesis 非法投掷物」",
    "story-reimuB-stage4-4-1": "＊现世的神秘主义者＊",
    "story-reimuB-stage4-5-1": "＊深秘的七大不可思议＊"
}